BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE mock_checkout ADD (cart_version NUMBER)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
-- +YOBI STATEMENT
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE mock_checkout ADD (cart_fingerprint VARCHAR2(64))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
-- +YOBI STATEMENT
BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX uq_checkout_cart_version ON mock_checkout(cart_id,cart_version)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
