TOOLS = [
    {
        "type": "function",
        "name": "recommend_menu_categories",
        "description": "Recommend 2-4 grounded synthetic menu categories after hard constraints.",
        "parameters": {
            "type": "object",
            "properties": {
                "query": {"type": "string"},
                "budget_krw": {"type": ["integer", "null"]},
                "max_spiciness": {"type": ["integer", "null"], "minimum": 0, "maximum": 5},
                "excluded_ingredients": {"type": "array", "items": {"type": "string"}},
                "servings": {"type": "integer", "minimum": 1, "maximum": 10},
                "desired_temperature": {"type": "string", "enum": ["warm", "cold", "any"]},
                "desired_texture": {"type": "array", "items": {"type": "string"}},
                "desired_flavors": {"type": "array", "items": {"type": "string"}},
            },
            "required": ["query", "budget_krw", "max_spiciness", "excluded_ingredients", "servings", "desired_temperature", "desired_texture", "desired_flavors"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "search_menus",
        "description": "Search the synthetic menu catalog with server-enforced constraints.",
        "parameters": {
            "type": "object",
            "properties": {
                "query": {"type": "string"},
                "budget_krw": {"type": ["integer", "null"]},
                "max_spiciness": {"type": ["integer", "null"], "minimum": 0, "maximum": 5},
                "excluded_ingredients": {"type": "array", "items": {"type": "string"}},
            },
            "required": ["query", "budget_krw", "max_spiciness", "excluded_ingredients"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "explain_menu",
        "description": "Explain one real seeded menu with cultural analogy and evidence IDs.",
        "parameters": {
            "type": "object",
            "properties": {"menu_id": {"type": "string"}},
            "required": ["menu_id"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "get_dietary_evidence",
        "description": "Retrieve source-linked dietary evidence for a seeded menu.",
        "parameters": {
            "type": "object",
            "properties": {"menu_id": {"type": "string"}},
            "required": ["menu_id"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "compare_merchants",
        "description": "Compare merchants on shared seeded axes for a menu category.",
        "parameters": {
            "type": "object",
            "properties": {"category": {"type": "string"}},
            "required": ["category"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "get_menu_options",
        "description": "Load authoritative option groups and price deltas for a menu.",
        "parameters": {
            "type": "object",
            "properties": {"menu_id": {"type": "string"}},
            "required": ["menu_id"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "translate_order_note",
        "description": "Translate an order or courier note and return a back translation for confirmation.",
        "parameters": {
            "type": "object",
            "properties": {
                "user_note": {"type": "string"},
                "target_context": {"type": "string", "enum": ["restaurant", "courier"]},
                "tone": {"type": "string", "enum": ["polite", "concise"]},
            },
            "required": ["user_note", "target_context", "tone"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "resolve_address",
        "description": "Resolve a hotel name or OCR text to synthetic address candidates; never auto-confirm.",
        "parameters": {
            "type": "object",
            "properties": {"text": {"type": "string"}},
            "required": ["text"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "get_cart_preview",
        "description": "Read the server-calculated cart snapshot and missing required slots.",
        "parameters": {"type": "object", "properties": {}, "additionalProperties": False},
        "strict": True,
    },
    {
        "type": "function",
        "name": "get_mock_payment_status",
        "description": "Read a synthetic checkout status without changing payment or order state.",
        "parameters": {
            "type": "object",
            "properties": {"checkout_id": {"type": "string"}},
            "required": ["checkout_id"],
            "additionalProperties": False,
        },
        "strict": True,
    },
]
