TOOLS = [
    {
        "type": "function",
        "name": "recommend_menu_categories",
        "description": "Recommend 2-4 grounded synthetic menu categories after hard constraints.",
        "parameters": {
            "type": "object",
            "properties": {
                "query": {"type": "string"},
                "budget_krw": {"type": ["integer", "null"]},
                "max_spiciness": {"type": ["integer", "null"], "minimum": 0, "maximum": 5},
                "excluded_ingredients": {"type": "array", "items": {"type": "string"}},
                "servings": {"type": "integer", "minimum": 1, "maximum": 10},
                "desired_temperature": {"type": "string", "enum": ["warm", "cold", "any"]},
                "desired_texture": {"type": "array", "items": {"type": "string"}},
                "desired_flavors": {"type": "array", "items": {"type": "string"}},
            },
            "required": ["query", "budget_krw", "max_spiciness", "excluded_ingredients", "servings", "desired_temperature", "desired_texture", "desired_flavors"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "search_menus",
        "description": "Search the synthetic menu catalog with server-enforced constraints.",
        "parameters": {
            "type": "object",
            "properties": {
                "query": {"type": "string"},
                "budget_krw": {"type": ["integer", "null"]},
                "max_spiciness": {"type": ["integer", "null"], "minimum": 0, "maximum": 5},
                "excluded_ingredients": {"type": "array", "items": {"type": "string"}},
            },
            "required": ["query", "budget_krw", "max_spiciness", "excluded_ingredients"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "explain_menu",
        "description": "Explain one real seeded menu with cultural analogy and evidence IDs.",
        "parameters": {
            "type": "object",
            "properties": {"menu_id": {"type": "string"}},
            "required": ["menu_id"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "get_dietary_evidence",
        "description": "Retrieve source-linked dietary evidence for a seeded menu.",
        "parameters": {
            "type": "object",
            "properties": {"menu_id": {"type": "string"}},
            "required": ["menu_id"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "compare_merchants",
        "description": "Compare merchants on shared seeded axes for a menu category.",
        "parameters": {
            "type": "object",
            "properties": {"category": {"type": "string"}},
            "required": ["category"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "get_menu_options",
        "description": "Load authoritative option groups and price deltas for a menu.",
        "parameters": {
            "type": "object",
            "properties": {"menu_id": {"type": "string"}},
            "required": ["menu_id"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "translate_order_note",
        "description": "Translate an order or courier note and return a back translation for confirmation.",
        "parameters": {
            "type": "object",
            "properties": {
                "user_note": {"type": "string"},
                "target_context": {"type": "string", "enum": ["restaurant", "courier"]},
                "tone": {"type": "string", "enum": ["polite", "concise"]},
            },
            "required": ["user_note", "target_context", "tone"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "resolve_address",
        "description": "Resolve a hotel name or OCR text to synthetic address candidates; never auto-confirm.",
        "parameters": {
            "type": "object",
            "properties": {"text": {"type": "string"}},
            "required": ["text"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "update_cart",
        "description": "Apply an explicit user cart request. The server validates options and recalculates every price.",
        "parameters": {
            "type": "object",
            "properties": {
                "action": {"type": "string", "enum": ["ADD_ITEM", "CHANGE_QUANTITY", "SELECT_OPTION", "REMOVE_OPTION", "REMOVE_ITEM", "ADD_NOTE", "CLEAR"]},
                "menu_id": {"type": ["string", "null"]},
                "cart_item_id": {"type": ["string", "null"]},
                "quantity": {"type": ["integer", "null"], "minimum": 1, "maximum": 10},
                "option_item_id": {"type": ["string", "null"]},
                "option_item_ids": {"type": "array", "items": {"type": "string"}},
                "note": {"type": ["string", "null"]},
            },
            "required": ["action", "menu_id", "cart_item_id", "quantity", "option_item_id", "option_item_ids", "note"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "update_delivery_preferences",
        "description": "Save explicit synthetic-delivery handoff preferences; the address still requires user confirmation.",
        "parameters": {
            "type": "object",
            "properties": {
                "address_ref_id": {"type": ["string", "null"]},
                "handoff_method": {"type": "string", "enum": ["front_desk", "door", "meet_outside"]},
                "cutlery": {"type": "boolean"},
                "ring_bell": {"type": "boolean"},
                "front_desk": {"type": "boolean"},
                "note": {"type": "string"},
            },
            "required": ["address_ref_id", "handoff_method", "cutlery", "ring_bell", "front_desk", "note"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "get_cart_preview",
        "description": "Read the server-calculated cart snapshot and missing required slots.",
        "parameters": {"type": "object", "properties": {}, "additionalProperties": False},
        "strict": True,
    },
    {
        "type": "function",
        "name": "get_mock_payment_status",
        "description": "Read a synthetic checkout status without changing payment or order state.",
        "parameters": {
            "type": "object",
            "properties": {"checkout_id": {"type": "string"}},
            "required": ["checkout_id"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "create_mock_checkout",
        "description": "Create an idempotent demo checkout only after the user-confirmed cart passes server revalidation.",
        "parameters": {
            "type": "object",
            "properties": {
                "idempotency_key": {"type": "string"},
                "payment_method": {"type": "string", "enum": ["international_card", "apple_pay_demo", "paypal_demo"]},
            },
            "required": ["idempotency_key", "payment_method"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "complete_mock_order",
        "description": "Return the one existing demo order after payment succeeds; never marks payment successful itself.",
        "parameters": {
            "type": "object",
            "properties": {"checkout_id": {"type": "string"}},
            "required": ["checkout_id"],
            "additionalProperties": False,
        },
        "strict": True,
    },
]
