import type { SupportedLanguage } from "./locale";

export interface ChatMenuCopy {
  open: string;
  close: string;
  weekly: string;
  kpop: string;
  editProfile: string;
  weeklyPrompt: string;
  weeklyResponse: string;
  kpopPrompt: string;
  kpopResponse: string;
  swipe: string;
  rank: string;
  currentAddress: string;
  keepAddress: string;
  changeAddress: string;
  saveChanges: string;
  changesSaved: string;
}

const en: ChatMenuCopy = {
  open:"Chat menu",close:"Close chat menu",weekly:"Weekly ranking",kpop:"K-POP Demon Hunters",editProfile:"Edit my information",
  weeklyPrompt:"Show me this week's delivery ranking",weeklyResponse:"Here is this week's delivery ranking. Swipe through a nearby delivery menu from each ranked restaurant.",
  kpopPrompt:"Show me the foods from K-POP Demon Hunters",kpopResponse:"Meet five Korean foods from K-POP Demon Hunters. Swipe through nearby delivery menus for each food.",
  swipe:"Swipe to explore all five menus",rank:"Rank",currentAddress:"Current delivery address",keepAddress:"Keep this address",changeAddress:"Change address",saveChanges:"Save changes",changesSaved:"Your information has been updated.",
};

const packs: Record<SupportedLanguage, ChatMenuCopy> = {
  English: en,
  "한국어": {open:"채팅방 메뉴",close:"채팅방 메뉴 닫기",weekly:"금주의 순위",kpop:"K-POP 데몬 헌터스",editProfile:"내 정보 수정",weeklyPrompt:"이번 주 배달 메뉴 순위 보여줘",weeklyResponse:"이번 주 배달 메뉴 순위예요. 순위별 근처 배달 메뉴를 옆으로 넘겨 확인해 보세요.",kpopPrompt:"K-POP 데몬 헌터스에 나온 음식 알려줘",kpopResponse:"K-POP 데몬 헌터스의 한국 음식 다섯 가지를 소개할게요. 음식별 근처 배달 메뉴를 옆으로 넘겨 보세요.",swipe:"옆으로 넘겨 다섯 메뉴 모두 보기",rank:"순위",currentAddress:"현재 배달 주소",keepAddress:"이 주소 그대로 사용",changeAddress:"주소 변경",saveChanges:"변경사항 저장",changesSaved:"내 정보가 수정됐어요."},
  "日本語": {...en,open:"チャットメニュー",close:"チャットメニューを閉じる",weekly:"今週のランキング",kpop:"K-POP デーモン・ハンターズ",editProfile:"情報を編集",weeklyPrompt:"今週の配達ランキングを見せて",weeklyResponse:"今週の配達ランキングです。各店の近くの配達メニューをスワイプしてご覧ください。",kpopPrompt:"K-POP デーモン・ハンターズの料理を見せて",kpopResponse:"作品に登場する5つの韓国料理をご紹介します。配達メニューをスワイプしてご覧ください。",swipe:"スワイプして5つのメニューを見る",rank:"順位",currentAddress:"現在の配達先",keepAddress:"この住所を使う",changeAddress:"住所を変更",saveChanges:"変更を保存",changesSaved:"情報を更新しました。"},
  "中文（简体）": {...en,open:"聊天菜单",close:"关闭聊天菜单",weekly:"本周排行",kpop:"K-POP 猎魔女团",editProfile:"修改我的信息",weeklyPrompt:"显示本周外卖排行",weeklyResponse:"这是本周外卖排行。左右滑动查看各店附近可配送菜单。",kpopPrompt:"介绍 K-POP 猎魔女团中的美食",kpopResponse:"为你介绍其中的五种韩国美食。左右滑动查看附近配送菜单。",swipe:"滑动查看全部五个菜单",rank:"排名",currentAddress:"当前配送地址",keepAddress:"保留此地址",changeAddress:"更改地址",saveChanges:"保存更改",changesSaved:"你的信息已更新。"},
  "中文（繁體）": {...en,open:"聊天選單",close:"關閉聊天選單",weekly:"本週排行",kpop:"K-POP 獵魔女團",editProfile:"修改我的資訊",weeklyPrompt:"顯示本週外送排行",weeklyResponse:"這是本週外送排行。左右滑動查看各店附近可配送菜單。",kpopPrompt:"介紹 K-POP 獵魔女團中的美食",kpopResponse:"為你介紹其中的五種韓國美食。左右滑動查看附近外送菜單。",swipe:"滑動查看全部五個菜單",rank:"排名",currentAddress:"目前配送地址",keepAddress:"保留此地址",changeAddress:"更改地址",saveChanges:"儲存變更",changesSaved:"你的資訊已更新。"},
  Español: {...en,open:"Menú del chat",close:"Cerrar menú",weekly:"Ranking semanal",kpop:"K-POP Demon Hunters",editProfile:"Editar mis datos",weeklyPrompt:"Muéstrame el ranking semanal de entregas",weeklyResponse:"Este es el ranking semanal. Desliza para ver un menú cercano de cada restaurante.",kpopPrompt:"Muéstrame la comida de K-POP Demon Hunters",kpopResponse:"Descubre cinco platos coreanos de K-POP Demon Hunters y sus menús cercanos.",swipe:"Desliza para ver los cinco menús",rank:"Puesto",currentAddress:"Dirección actual",keepAddress:"Conservar dirección",changeAddress:"Cambiar dirección",saveChanges:"Guardar cambios",changesSaved:"Tus datos se actualizaron."},
  Français: {...en,open:"Menu du chat",close:"Fermer le menu",weekly:"Classement de la semaine",kpop:"K-POP Demon Hunters",editProfile:"Modifier mes informations",weeklyPrompt:"Montre le classement des livraisons",weeklyResponse:"Voici le classement de la semaine. Faites glisser pour voir un menu proche de chaque restaurant.",kpopPrompt:"Montre les plats de K-POP Demon Hunters",kpopResponse:"Découvrez cinq plats coréens de K-POP Demon Hunters et leurs menus en livraison.",swipe:"Faites glisser les cinq menus",rank:"Rang",currentAddress:"Adresse actuelle",keepAddress:"Garder cette adresse",changeAddress:"Changer l’adresse",saveChanges:"Enregistrer",changesSaved:"Vos informations ont été mises à jour."},
  Deutsch: {...en,open:"Chat-Menü",close:"Chat-Menü schließen",weekly:"Wochenranking",kpop:"K-POP Demon Hunters",editProfile:"Meine Angaben ändern",weeklyPrompt:"Zeig mir das Liefer-Ranking der Woche",weeklyResponse:"Hier ist das Wochenranking. Wische durch ein Liefermenü jedes Restaurants.",kpopPrompt:"Zeig mir Gerichte aus K-POP Demon Hunters",kpopResponse:"Entdecke fünf koreanische Gerichte aus K-POP Demon Hunters und passende Liefermenüs.",swipe:"Durch alle fünf Menüs wischen",rank:"Rang",currentAddress:"Aktuelle Lieferadresse",keepAddress:"Adresse behalten",changeAddress:"Adresse ändern",saveChanges:"Änderungen speichern",changesSaved:"Deine Angaben wurden aktualisiert."},
  Italiano: {...en,open:"Menu chat",close:"Chiudi menu",weekly:"Classifica settimanale",kpop:"K-POP Demon Hunters",editProfile:"Modifica i miei dati",weeklyPrompt:"Mostra la classifica settimanale",weeklyResponse:"Ecco la classifica della settimana. Scorri un menu vicino per ogni ristorante.",kpopPrompt:"Mostra i cibi di K-POP Demon Hunters",kpopResponse:"Scopri cinque piatti coreani di K-POP Demon Hunters e i menu in consegna.",swipe:"Scorri tutti e cinque i menu",rank:"Posizione",currentAddress:"Indirizzo attuale",keepAddress:"Mantieni indirizzo",changeAddress:"Cambia indirizzo",saveChanges:"Salva modifiche",changesSaved:"I tuoi dati sono stati aggiornati."},
  Português: {...en,open:"Menu do chat",close:"Fechar menu",weekly:"Ranking semanal",kpop:"K-POP Demon Hunters",editProfile:"Editar meus dados",weeklyPrompt:"Mostre o ranking semanal de entregas",weeklyResponse:"Este é o ranking da semana. Deslize para ver um menu próximo de cada restaurante.",kpopPrompt:"Mostre as comidas de K-POP Demon Hunters",kpopResponse:"Conheça cinco comidas coreanas de K-POP Demon Hunters e menus próximos.",swipe:"Deslize pelos cinco menus",rank:"Posição",currentAddress:"Endereço atual",keepAddress:"Manter endereço",changeAddress:"Alterar endereço",saveChanges:"Salvar alterações",changesSaved:"Seus dados foram atualizados."},
  "ไทย": {...en,open:"เมนูแชต",close:"ปิดเมนูแชต",weekly:"อันดับประจำสัปดาห์",kpop:"K-POP Demon Hunters",editProfile:"แก้ไขข้อมูลของฉัน",weeklyPrompt:"แสดงอันดับเดลิเวอรีประจำสัปดาห์",weeklyResponse:"นี่คืออันดับประจำสัปดาห์ ปัดดูเมนูจัดส่งใกล้คุณจากแต่ละร้าน",kpopPrompt:"แสดงอาหารจาก K-POP Demon Hunters",kpopResponse:"พบกับอาหารเกาหลีห้าอย่างจาก K-POP Demon Hunters และเมนูจัดส่งใกล้คุณ",swipe:"ปัดดูเมนูทั้งห้า",rank:"อันดับ",currentAddress:"ที่อยู่จัดส่งปัจจุบัน",keepAddress:"ใช้ที่อยู่นี้",changeAddress:"เปลี่ยนที่อยู่",saveChanges:"บันทึกการเปลี่ยนแปลง",changesSaved:"อัปเดตข้อมูลแล้ว"},
  "Tiếng Việt": {...en,open:"Menu trò chuyện",close:"Đóng menu",weekly:"Xếp hạng tuần",kpop:"K-POP Demon Hunters",editProfile:"Sửa thông tin",weeklyPrompt:"Cho tôi xem xếp hạng giao đồ ăn tuần này",weeklyResponse:"Đây là xếp hạng tuần này. Vuốt để xem món giao gần bạn từ từng nhà hàng.",kpopPrompt:"Cho tôi xem món ăn trong K-POP Demon Hunters",kpopResponse:"Khám phá năm món Hàn trong K-POP Demon Hunters và thực đơn giao gần bạn.",swipe:"Vuốt xem cả năm thực đơn",rank:"Hạng",currentAddress:"Địa chỉ hiện tại",keepAddress:"Giữ địa chỉ này",changeAddress:"Đổi địa chỉ",saveChanges:"Lưu thay đổi",changesSaved:"Thông tin đã được cập nhật."},
  "Bahasa Indonesia": {...en,open:"Menu chat",close:"Tutup menu",weekly:"Peringkat mingguan",kpop:"K-POP Demon Hunters",editProfile:"Edit informasi saya",weeklyPrompt:"Tampilkan peringkat pengantaran minggu ini",weeklyResponse:"Inilah peringkat minggu ini. Geser untuk melihat menu terdekat dari setiap restoran.",kpopPrompt:"Tampilkan makanan dari K-POP Demon Hunters",kpopResponse:"Kenali lima makanan Korea dari K-POP Demon Hunters dan menu terdekat.",swipe:"Geser kelima menu",rank:"Peringkat",currentAddress:"Alamat saat ini",keepAddress:"Gunakan alamat ini",changeAddress:"Ubah alamat",saveChanges:"Simpan perubahan",changesSaved:"Informasi Anda diperbarui."},
  "العربية": {...en,open:"قائمة المحادثة",close:"إغلاق القائمة",weekly:"ترتيب الأسبوع",kpop:"K-POP Demon Hunters",editProfile:"تعديل معلوماتي",weeklyPrompt:"أظهر ترتيب التوصيل لهذا الأسبوع",weeklyResponse:"هذا ترتيب الأسبوع. مرر لرؤية وجبة توصيل قريبة من كل مطعم.",kpopPrompt:"أظهر أطعمة K-POP Demon Hunters",kpopResponse:"تعرّف إلى خمسة أطعمة كورية من K-POP Demon Hunters وقوائم توصيل قريبة.",swipe:"مرر لرؤية القوائم الخمس",rank:"الترتيب",currentAddress:"عنوان التوصيل الحالي",keepAddress:"الاحتفاظ بالعنوان",changeAddress:"تغيير العنوان",saveChanges:"حفظ التغييرات",changesSaved:"تم تحديث معلوماتك."},
  "हिन्दी": {...en,open:"चैट मेनू",close:"चैट मेनू बंद करें",weekly:"साप्ताहिक रैंकिंग",kpop:"K-POP Demon Hunters",editProfile:"मेरी जानकारी बदलें",weeklyPrompt:"इस सप्ताह की डिलीवरी रैंकिंग दिखाएँ",weeklyResponse:"यह इस सप्ताह की रैंकिंग है। हर रेस्तरां का पास का डिलीवरी मेनू स्वाइप करके देखें।",kpopPrompt:"K-POP Demon Hunters के भोजन दिखाएँ",kpopResponse:"K-POP Demon Hunters के पाँच कोरियाई भोजन और पास के डिलीवरी मेनू देखें।",swipe:"सभी पाँच मेनू स्वाइप करें",rank:"रैंक",currentAddress:"मौजूदा डिलीवरी पता",keepAddress:"यही पता रखें",changeAddress:"पता बदलें",saveChanges:"बदलाव सहेजें",changesSaved:"आपकी जानकारी अपडेट हो गई।"},
  "Русский": {...en,open:"Меню чата",close:"Закрыть меню",weekly:"Рейтинг недели",kpop:"K-POP Demon Hunters",editProfile:"Изменить мои данные",weeklyPrompt:"Покажи рейтинг доставки недели",weeklyResponse:"Вот рейтинг недели. Листайте ближайшее меню доставки каждого ресторана.",kpopPrompt:"Покажи еду из K-POP Demon Hunters",kpopResponse:"Познакомьтесь с пятью корейскими блюдами из K-POP Demon Hunters и ближайшими меню.",swipe:"Листайте все пять меню",rank:"Место",currentAddress:"Текущий адрес",keepAddress:"Оставить адрес",changeAddress:"Изменить адрес",saveChanges:"Сохранить",changesSaved:"Ваши данные обновлены."},
};

export function getChatMenuCopy(language: SupportedLanguage) {
  return packs[language];
}
