import { asEffectiveLanguage, type SupportedLanguage } from "./locale";

export interface SelectionCopy {
  preferNot: string;
  religions: string[];
  religionValues: string[];
  favouritesPlaceholder: string;
  addressDescription: string;
  hotelOrStay: string;
  chooseImage: string;
  useDemoImage: string;
  fullRoad: string;
  postalCode: string;
  city: string;
  syntheticPlace: string;
  confirmStart: string;
  checkingContext: string;
  saveStart: string;
  addressNotFound: string;
  addressError: string;
  confirmError: string;
  demoImageError: string;
}

export interface JourneyCopy {
  catalogReady: string; openCart: string; chooseFirst: string; fallbackMode: string; sendMessage: string;
  failedCheck: string; demoPrompt: string; catalogSources: string; previousMenu: string; nextMenu: string;
  syntheticMenu: string; portion: string; sideBySide: string; bestFit: string; flavour: string;
  notVerified: string; verified: string; riskSignal: string; conflicting: string; included: string;
  blocked: string; unlocked: string; unlock: string; restaurantNote: string; howSay: string;
  messageRestaurant: string; backTranslation: string; mildNote: string; handoffQuestion: string;
  hotelFrontDesk: string; noBellCutlery: string; messageCourier: string; reviewTitle: string;
  quantity: string; decrease: string; increase: string; remove: string; items: string; total: string;
  dietaryCheck: string; removeConflict: string; noConflict: string; restaurantMinimum: string;
  add: string; met: string; noMinimum: string; completeRequirements: string; loading: string;
  secureCheckout: string; paymentSimulation: string; internationalCard: string; applePayDemo: string;
  presentationAvailable: string; privacy: string; paymentFailed: string; mockConfirmed: string;
  etaDemo: string; frontDeskHandoff: string; paymentSuccess: string; retry: string;
}

const religionValues = ["No specific religion", "Islam", "Judaism", "Hinduism", "Buddhism", "Christianity", "Sikhism", "Jainism", "Other"];

const selectionBase: Record<SupportedLanguage, Omit<SelectionCopy, "religionValues">> = {
  English: {preferNot:"Prefer not to say",religions:["No specific religion","Islam","Judaism","Hinduism","Buddhism","Christianity","Sikhism","Jainism","Other"],favouritesPlaceholder:"e.g. noodles, dumplings, crispy chicken",addressDescription:"Confirm where the food should arrive before choosing a menu.",hotelOrStay:"Hotel or accommodation",chooseImage:"Choose a booking image",useDemoImage:"Use the demo booking image",fullRoad:"Full road address",postalCode:"Postal code",city:"City",syntheticPlace:"synthetic place",confirmStart:"Confirm & start",checkingContext:"Checking your context…",saveStart:"Save and start",addressNotFound:"No matching address was found. Try the full hotel name or enter the road address.",addressError:"We could not check that address. Try another method.",confirmError:"Search for the address again, then confirm the matching result.",demoImageError:"The demo address could not be checked. Try the hotel search."},
  "한국어": {preferNot:"응답하지 않음",religions:["특정 종교 없음","이슬람교","유대교","힌두교","불교","기독교","시크교","자이나교","기타"],favouritesPlaceholder:"예: 면 요리, 만두, 바삭한 치킨",addressDescription:"메뉴를 고르기 전에 음식이 도착할 장소를 확인해 주세요.",hotelOrStay:"호텔 또는 숙소",chooseImage:"예약 이미지 선택",useDemoImage:"데모 예약 이미지 사용",fullRoad:"도로명 주소 전체",postalCode:"우편번호",city:"도시",syntheticPlace:"합성 데모 장소",confirmStart:"확인하고 시작",checkingContext:"입력 정보를 확인하는 중…",saveStart:"저장하고 시작",addressNotFound:"일치하는 주소를 찾지 못했어요. 호텔 이름 전체를 검색하거나 도로명 주소를 입력해 주세요.",addressError:"주소를 확인하지 못했어요. 다른 방법을 이용해 주세요.",confirmError:"주소를 다시 검색한 뒤 일치하는 결과를 확인해 주세요.",demoImageError:"데모 주소를 확인하지 못했어요. 호텔 검색을 이용해 주세요."},
  "日本語": {preferNot:"回答しない",religions:["特定の宗教なし","イスラム教","ユダヤ教","ヒンドゥー教","仏教","キリスト教","シク教","ジャイナ教","その他"],favouritesPlaceholder:"例：麺、餃子、フライドチキン",addressDescription:"メニューを選ぶ前に配達先を確認してください。",hotelOrStay:"ホテル・宿泊先",chooseImage:"予約画像を選択",useDemoImage:"デモ予約画像を使用",fullRoad:"道路名住所",postalCode:"郵便番号",city:"市区町村",syntheticPlace:"合成デモ地点",confirmStart:"確認して開始",checkingContext:"入力内容を確認中…",saveStart:"保存して開始",addressNotFound:"一致する住所がありません。ホテルの正式名か道路名住所を入力してください。",addressError:"住所を確認できませんでした。別の方法をお試しください。",confirmError:"住所を再検索し、一致する結果を確認してください。",demoImageError:"デモ住所を確認できませんでした。ホテル検索をお試しください。"},
  "中文（简体）": {preferNot:"不愿透露",religions:["无特定宗教","伊斯兰教","犹太教","印度教","佛教","基督教","锡克教","耆那教","其他"],favouritesPlaceholder:"例如：面条、饺子、炸鸡",addressDescription:"选择菜单前，请先确认送餐地点。",hotelOrStay:"酒店或住宿",chooseImage:"选择预订图片",useDemoImage:"使用演示预订图片",fullRoad:"完整道路地址",postalCode:"邮政编码",city:"城市",syntheticPlace:"合成演示地点",confirmStart:"确认并开始",checkingContext:"正在核对信息…",saveStart:"保存并开始",addressNotFound:"未找到匹配地址。请尝试酒店全名或输入道路地址。",addressError:"无法核对该地址，请尝试其他方式。",confirmError:"请重新搜索地址并确认匹配结果。",demoImageError:"无法核对演示地址，请尝试酒店搜索。"},
  "中文（繁體）": {preferNot:"不願透露",religions:["無特定宗教","伊斯蘭教","猶太教","印度教","佛教","基督教","錫克教","耆那教","其他"],favouritesPlaceholder:"例如：麵、餃子、炸雞",addressDescription:"選擇菜單前，請先確認送餐地點。",hotelOrStay:"飯店或住宿",chooseImage:"選擇預訂圖片",useDemoImage:"使用示範預訂圖片",fullRoad:"完整道路地址",postalCode:"郵遞區號",city:"城市",syntheticPlace:"合成示範地點",confirmStart:"確認並開始",checkingContext:"正在核對資訊…",saveStart:"儲存並開始",addressNotFound:"找不到符合的地址。請嘗試飯店全名或輸入道路地址。",addressError:"無法核對該地址，請嘗試其他方式。",confirmError:"請重新搜尋地址並確認符合的結果。",demoImageError:"無法核對示範地址，請嘗試飯店搜尋。"},
  Español: {preferNot:"Prefiero no decirlo",religions:["Sin religión específica","Islam","Judaísmo","Hinduismo","Budismo","Cristianismo","Sijismo","Jainismo","Otra"],favouritesPlaceholder:"p. ej., fideos, dumplings, pollo crujiente",addressDescription:"Confirma dónde debe llegar la comida antes de elegir el menú.",hotelOrStay:"Hotel o alojamiento",chooseImage:"Elegir imagen de reserva",useDemoImage:"Usar imagen de reserva demo",fullRoad:"Dirección completa",postalCode:"Código postal",city:"Ciudad",syntheticPlace:"lugar sintético",confirmStart:"Confirmar y empezar",checkingContext:"Comprobando tus datos…",saveStart:"Guardar y empezar",addressNotFound:"No encontramos esa dirección. Prueba el nombre completo del hotel o la dirección.",addressError:"No pudimos comprobar la dirección. Prueba otro método.",confirmError:"Busca de nuevo la dirección y confirma el resultado correcto.",demoImageError:"No pudimos comprobar la dirección demo. Prueba la búsqueda de hotel."},
  Français: {preferNot:"Je préfère ne pas répondre",religions:["Aucune religion particulière","Islam","Judaïsme","Hindouisme","Bouddhisme","Christianisme","Sikhisme","Jaïnisme","Autre"],favouritesPlaceholder:"ex. nouilles, raviolis, poulet croustillant",addressDescription:"Confirmez le lieu de livraison avant de choisir un plat.",hotelOrStay:"Hôtel ou hébergement",chooseImage:"Choisir une image de réservation",useDemoImage:"Utiliser l’image de réservation démo",fullRoad:"Adresse complète",postalCode:"Code postal",city:"Ville",syntheticPlace:"lieu synthétique",confirmStart:"Confirmer et commencer",checkingContext:"Vérification de vos informations…",saveStart:"Enregistrer et commencer",addressNotFound:"Aucune adresse correspondante. Essayez le nom complet de l’hôtel ou l’adresse.",addressError:"Impossible de vérifier cette adresse. Essayez une autre méthode.",confirmError:"Recherchez à nouveau l’adresse puis confirmez le bon résultat.",demoImageError:"Impossible de vérifier l’adresse démo. Essayez la recherche d’hôtel."},
  Deutsch: {preferNot:"Keine Angabe",religions:["Keine bestimmte Religion","Islam","Judentum","Hinduismus","Buddhismus","Christentum","Sikhismus","Jainismus","Andere"],favouritesPlaceholder:"z. B. Nudeln, Teigtaschen, knuspriges Hähnchen",addressDescription:"Bestätige vor der Menüwahl den Lieferort.",hotelOrStay:"Hotel oder Unterkunft",chooseImage:"Buchungsbild auswählen",useDemoImage:"Demo-Buchungsbild verwenden",fullRoad:"Vollständige Adresse",postalCode:"Postleitzahl",city:"Stadt",syntheticPlace:"synthetischer Demo-Ort",confirmStart:"Bestätigen und starten",checkingContext:"Angaben werden geprüft…",saveStart:"Speichern und starten",addressNotFound:"Keine passende Adresse gefunden. Nutze den vollständigen Hotelnamen oder die Adresse.",addressError:"Die Adresse konnte nicht geprüft werden. Nutze eine andere Methode.",confirmError:"Suche erneut und bestätige das passende Ergebnis.",demoImageError:"Die Demo-Adresse konnte nicht geprüft werden. Nutze die Hotelsuche."},
  Italiano: {preferNot:"Preferisco non dirlo",religions:["Nessuna religione specifica","Islam","Ebraismo","Induismo","Buddismo","Cristianesimo","Sikhismo","Giainismo","Altra"],favouritesPlaceholder:"es. noodles, ravioli, pollo croccante",addressDescription:"Conferma il luogo di consegna prima di scegliere il menu.",hotelOrStay:"Hotel o alloggio",chooseImage:"Scegli immagine prenotazione",useDemoImage:"Usa immagine prenotazione demo",fullRoad:"Indirizzo completo",postalCode:"CAP",city:"Città",syntheticPlace:"luogo sintetico",confirmStart:"Conferma e inizia",checkingContext:"Controllo dei dati…",saveStart:"Salva e inizia",addressNotFound:"Nessun indirizzo corrispondente. Prova il nome completo dell’hotel o l’indirizzo.",addressError:"Impossibile controllare l’indirizzo. Prova un altro metodo.",confirmError:"Cerca di nuovo l’indirizzo e conferma il risultato corretto.",demoImageError:"Impossibile controllare l’indirizzo demo. Prova la ricerca hotel."},
  Português: {preferNot:"Prefiro não dizer",religions:["Sem religião específica","Islã","Judaísmo","Hinduísmo","Budismo","Cristianismo","Siquismo","Jainismo","Outra"],favouritesPlaceholder:"ex.: macarrão, dumplings, frango crocante",addressDescription:"Confirme onde a comida deve chegar antes de escolher o menu.",hotelOrStay:"Hotel ou hospedagem",chooseImage:"Escolher imagem da reserva",useDemoImage:"Usar imagem de reserva demo",fullRoad:"Endereço completo",postalCode:"Código postal",city:"Cidade",syntheticPlace:"local sintético",confirmStart:"Confirmar e começar",checkingContext:"Verificando seus dados…",saveStart:"Salvar e começar",addressNotFound:"Endereço não encontrado. Tente o nome completo do hotel ou o endereço.",addressError:"Não foi possível verificar o endereço. Tente outro método.",confirmError:"Pesquise novamente e confirme o resultado correto.",demoImageError:"Não foi possível verificar o endereço demo. Tente a busca de hotel."},
  "ไทย": {preferNot:"ไม่ต้องการระบุ",religions:["ไม่มีศาสนาเฉพาะ","อิสลาม","ยิว","ฮินดู","พุทธ","คริสต์","ซิกข์","เชน","อื่น ๆ"],favouritesPlaceholder:"เช่น เส้น เกี๊ยว ไก่ทอดกรอบ",addressDescription:"ยืนยันสถานที่จัดส่งก่อนเลือกเมนู",hotelOrStay:"โรงแรมหรือที่พัก",chooseImage:"เลือกรูปการจอง",useDemoImage:"ใช้รูปการจองเดโม",fullRoad:"ที่อยู่แบบเต็ม",postalCode:"รหัสไปรษณีย์",city:"เมือง",syntheticPlace:"สถานที่สังเคราะห์",confirmStart:"ยืนยันและเริ่ม",checkingContext:"กำลังตรวจสอบข้อมูล…",saveStart:"บันทึกและเริ่ม",addressNotFound:"ไม่พบที่อยู่ ลองชื่อโรงแรมเต็มหรือกรอกที่อยู่",addressError:"ตรวจสอบที่อยู่ไม่ได้ โปรดลองวิธีอื่น",confirmError:"ค้นหาที่อยู่อีกครั้งและยืนยันผลที่ตรงกัน",demoImageError:"ตรวจสอบที่อยู่เดโมไม่ได้ โปรดลองค้นหาโรงแรม"},
  "Tiếng Việt": {preferNot:"Không muốn trả lời",religions:["Không theo tôn giáo cụ thể","Hồi giáo","Do Thái giáo","Ấn Độ giáo","Phật giáo","Cơ Đốc giáo","Sikh giáo","Kỳ Na giáo","Khác"],favouritesPlaceholder:"vd. mì, bánh xếp, gà giòn",addressDescription:"Xác nhận nơi giao món trước khi chọn thực đơn.",hotelOrStay:"Khách sạn hoặc chỗ ở",chooseImage:"Chọn ảnh đặt phòng",useDemoImage:"Dùng ảnh đặt phòng demo",fullRoad:"Địa chỉ đường đầy đủ",postalCode:"Mã bưu chính",city:"Thành phố",syntheticPlace:"địa điểm tổng hợp",confirmStart:"Xác nhận và bắt đầu",checkingContext:"Đang kiểm tra thông tin…",saveStart:"Lưu và bắt đầu",addressNotFound:"Không tìm thấy địa chỉ. Hãy thử tên đầy đủ của khách sạn hoặc nhập địa chỉ.",addressError:"Không thể kiểm tra địa chỉ. Hãy thử cách khác.",confirmError:"Hãy tìm lại địa chỉ và xác nhận kết quả phù hợp.",demoImageError:"Không thể kiểm tra địa chỉ demo. Hãy thử tìm khách sạn."},
  "Bahasa Indonesia": {preferNot:"Tidak ingin menjawab",religions:["Tanpa agama tertentu","Islam","Yudaisme","Hinduisme","Buddhisme","Kristen","Sikhisme","Jainisme","Lainnya"],favouritesPlaceholder:"mis. mi, pangsit, ayam renyah",addressDescription:"Konfirmasi tujuan makanan sebelum memilih menu.",hotelOrStay:"Hotel atau penginapan",chooseImage:"Pilih gambar reservasi",useDemoImage:"Gunakan gambar reservasi demo",fullRoad:"Alamat jalan lengkap",postalCode:"Kode pos",city:"Kota",syntheticPlace:"tempat sintetis",confirmStart:"Konfirmasi dan mulai",checkingContext:"Memeriksa informasi…",saveStart:"Simpan dan mulai",addressNotFound:"Alamat tidak ditemukan. Coba nama lengkap hotel atau masukkan alamat.",addressError:"Alamat tidak dapat diperiksa. Coba cara lain.",confirmError:"Cari alamat lagi lalu konfirmasi hasil yang sesuai.",demoImageError:"Alamat demo tidak dapat diperiksa. Coba pencarian hotel."},
  "العربية": {preferNot:"أفضل عدم الإجابة",religions:["لا ديانة محددة","الإسلام","اليهودية","الهندوسية","البوذية","المسيحية","السيخية","الجاينية","أخرى"],favouritesPlaceholder:"مثل المعكرونة والزلابية والدجاج المقرمش",addressDescription:"أكد مكان وصول الطعام قبل اختيار القائمة.",hotelOrStay:"الفندق أو مكان الإقامة",chooseImage:"اختر صورة الحجز",useDemoImage:"استخدم صورة الحجز التجريبية",fullRoad:"العنوان الكامل",postalCode:"الرمز البريدي",city:"المدينة",syntheticPlace:"مكان اصطناعي",confirmStart:"تأكيد وبدء",checkingContext:"جارٍ التحقق من المعلومات…",saveStart:"حفظ وبدء",addressNotFound:"لم نعثر على عنوان مطابق. جرّب اسم الفندق الكامل أو أدخل العنوان.",addressError:"تعذر التحقق من العنوان. جرّب طريقة أخرى.",confirmError:"ابحث عن العنوان مجددًا ثم أكد النتيجة المطابقة.",demoImageError:"تعذر التحقق من عنوان العرض. جرّب البحث عن الفندق."},
  "हिन्दी": {preferNot:"बताना नहीं चाहता/चाहती",religions:["कोई विशेष धर्म नहीं","इस्लाम","यहूदी धर्म","हिंदू धर्म","बौद्ध धर्म","ईसाई धर्म","सिख धर्म","जैन धर्म","अन्य"],favouritesPlaceholder:"जैसे नूडल्स, मोमो, कुरकुरा चिकन",addressDescription:"मेनू चुनने से पहले डिलीवरी स्थान पक्का करें।",hotelOrStay:"होटल या ठहरने की जगह",chooseImage:"बुकिंग चित्र चुनें",useDemoImage:"डेमो बुकिंग चित्र उपयोग करें",fullRoad:"पूरा सड़क पता",postalCode:"पिन कोड",city:"शहर",syntheticPlace:"सिंथेटिक स्थान",confirmStart:"पुष्टि करके शुरू करें",checkingContext:"जानकारी जाँची जा रही है…",saveStart:"सहेजकर शुरू करें",addressNotFound:"मिलता पता नहीं मिला। होटल का पूरा नाम या सड़क पता डालें।",addressError:"पता जाँचा नहीं जा सका। दूसरा तरीका आज़माएँ।",confirmError:"पता फिर खोजें और सही नतीजे की पुष्टि करें।",demoImageError:"डेमो पता जाँचा नहीं जा सका। होटल खोज आज़माएँ।"},
  "Русский": {preferNot:"Предпочитаю не отвечать",religions:["Нет определённой религии","Ислам","Иудаизм","Индуизм","Буддизм","Христианство","Сикхизм","Джайнизм","Другое"],favouritesPlaceholder:"например: лапша, пельмени, хрустящая курица",addressDescription:"Подтвердите место доставки перед выбором меню.",hotelOrStay:"Отель или жильё",chooseImage:"Выбрать изображение брони",useDemoImage:"Использовать демо бронирования",fullRoad:"Полный адрес",postalCode:"Почтовый индекс",city:"Город",syntheticPlace:"синтетическое место",confirmStart:"Подтвердить и начать",checkingContext:"Проверяем информацию…",saveStart:"Сохранить и начать",addressNotFound:"Адрес не найден. Введите полное название отеля или адрес.",addressError:"Не удалось проверить адрес. Попробуйте другой способ.",confirmError:"Найдите адрес снова и подтвердите подходящий результат.",demoImageError:"Не удалось проверить демо-адрес. Попробуйте поиск отеля."},
};

const enJourney: JourneyCopy = {catalogReady:"Demo catalog ready",openCart:"Open cart",chooseFirst:"Choose a menu first",fallbackMode:"Demo continuity mode",sendMessage:"Send message",failedCheck:"I couldn’t complete that check. Your selections are unchanged—please try again.",demoPrompt:"I saw people eating a red rice cake dish on the street. What is it, and can I order it?",catalogSources:"Catalog sources",previousMenu:"Previous menu",nextMenu:"Next menu",syntheticMenu:"Synthetic demo menu",portion:"Portion",sideBySide:"Side by side",bestFit:"Best fit",flavour:"Flavour",notVerified:"Not verified",verified:"Restaurant verified",riskSignal:"Risk signal",conflicting:"Conflicting information",included:"Included",blocked:"Blocked for your dietary profile",unlocked:"Unlocked by you — server checks still apply",unlock:"Unlock option",restaurantNote:"Restaurant note",howSay:"How should we say it?",messageRestaurant:"Message to restaurant",backTranslation:"Back translation",mildNote:"As mild as possible, please.",handoffQuestion:"Leave it at the front desk?",hotelFrontDesk:"Hotel front desk",noBellCutlery:"No bell · no disposable cutlery",messageCourier:"Message to courier",reviewTitle:"Everything still matches.",quantity:"Quantity",decrease:"Decrease quantity",increase:"Increase quantity",remove:"Remove",items:"Items",total:"Total",dietaryCheck:"Dietary check",removeConflict:"Remove the conflicting item or option.",noConflict:"No known hard conflict in the current cart.",restaurantMinimum:"Restaurant minimum",add:"add",met:"met",noMinimum:"No minimum available.",completeRequirements:"Complete the highlighted requirements before payment.",loading:"Loading…",secureCheckout:"Mock secure checkout",paymentSimulation:"External payment simulation",internationalCard:"International card",applePayDemo:"Apple Pay demo",presentationAvailable:"Available in presentation mode",privacy:"No card number, personal payment data, or real charge is processed.",paymentFailed:"Demo payment failed. Your cart is unchanged, so you can retry safely.",mockConfirmed:"Mock order confirmed",etaDemo:"About 35 minutes · synthetic ETA",frontDeskHandoff:"Leave with the YOBI Myeongdong Hotel front desk",paymentSuccess:"Demo payment successful · no real restaurant or courier was contacted",retry:"Please try again. Your previous selections are unchanged."};

const journeyPacks: Record<SupportedLanguage, JourneyCopy> = {
  English: enJourney,
  "한국어": {catalogReady:"데모 카탈로그 준비됨",openCart:"장바구니 열기",chooseFirst:"먼저 메뉴를 선택해 주세요",fallbackMode:"데모 연속 모드",sendMessage:"메시지 보내기",failedCheck:"확인을 완료하지 못했어요. 선택 내용은 그대로이니 다시 시도해 주세요.",demoPrompt:"길거리에서 빨간 떡 요리를 봤어요. 무슨 음식이고 주문할 수 있나요?",catalogSources:"카탈로그 출처",previousMenu:"이전 메뉴",nextMenu:"다음 메뉴",syntheticMenu:"합성 데모 메뉴",portion:"양",sideBySide:"한눈에 비교",bestFit:"가장 잘 맞음",flavour:"맛",notVerified:"확인되지 않음",verified:"가게 확인 완료",riskSignal:"위험 신호",conflicting:"상충하는 정보",included:"포함",blocked:"식이 정보와 충돌하여 비활성화됨",unlocked:"사용자가 잠금 해제함 · 서버 검사는 계속 적용",unlock:"옵션 잠금 해제",restaurantNote:"가게 요청 사항",howSay:"어떻게 전달할까요?",messageRestaurant:"가게에 보낼 메시지",backTranslation:"다시 번역",mildNote:"가능한 한 맵지 않게 해 주세요.",handoffQuestion:"프런트에 맡길까요?",hotelFrontDesk:"호텔 프런트",noBellCutlery:"벨 누르지 않기 · 일회용 수저 제외",messageCourier:"배달원에게 보낼 메시지",reviewTitle:"선택한 내용을 마지막으로 확인해 주세요.",quantity:"수량",decrease:"수량 줄이기",increase:"수량 늘리기",remove:"삭제",items:"메뉴 금액",total:"합계",dietaryCheck:"식이 조건 확인",removeConflict:"충돌하는 메뉴 또는 옵션을 삭제해 주세요.",noConflict:"현재 장바구니에 확인된 필수 충돌이 없습니다.",restaurantMinimum:"가게 최소 주문금액",add:"추가 필요",met:"충족",noMinimum:"최소 주문금액 정보 없음",completeRequirements:"표시된 조건을 해결한 뒤 결제해 주세요.",loading:"불러오는 중…",secureCheckout:"안전한 데모 결제",paymentSimulation:"외부 결제 시뮬레이션",internationalCard:"해외 결제 카드",applePayDemo:"Apple Pay 데모",presentationAvailable:"발표 모드에서 사용 가능",privacy:"카드 번호나 개인 결제 정보를 처리하지 않으며 실제로 결제되지 않습니다.",paymentFailed:"데모 결제에 실패했어요. 장바구니는 그대로이므로 안전하게 다시 시도할 수 있어요.",mockConfirmed:"데모 주문 확인 완료",etaDemo:"약 35분 · 합성 예상 시간",frontDeskHandoff:"YOBI 명동 호텔 프런트에 맡겨 주세요",paymentSuccess:"데모 결제 성공 · 실제 가게나 배달원에게 전달되지 않았습니다",retry:"다시 시도해 주세요. 이전 선택 내용은 그대로입니다."},
  "日本語": {...enJourney,catalogReady:"デモカタログ準備完了",openCart:"カートを開く",chooseFirst:"先にメニューを選んでください",fallbackMode:"デモ継続モード",sendMessage:"メッセージを送信",failedCheck:"確認を完了できませんでした。選択内容は変わっていません。もう一度お試しください。",demoPrompt:"街で赤い餅料理を見ました。何という料理で、注文できますか？",catalogSources:"カタログ情報源",previousMenu:"前のメニュー",nextMenu:"次のメニュー",syntheticMenu:"合成デモメニュー",portion:"量",sideBySide:"比較",bestFit:"最適",flavour:"味",notVerified:"未確認",verified:"店舗確認済み",riskSignal:"リスク情報",conflicting:"矛盾する情報",included:"含まれます",blocked:"食事条件により選択不可",unlocked:"ロック解除済み・サーバー確認は継続",unlock:"ロック解除",restaurantNote:"店舗への要望",howSay:"どう伝えますか？",messageRestaurant:"店舗へのメッセージ",backTranslation:"再翻訳",mildNote:"できるだけ辛くしないでください。",handoffQuestion:"フロントに預けますか？",hotelFrontDesk:"ホテルフロント",noBellCutlery:"呼び鈴なし・使い捨てカトラリー不要",messageCourier:"配達員へのメッセージ",reviewTitle:"選択内容を最終確認してください。",quantity:"数量",decrease:"数量を減らす",increase:"数量を増やす",remove:"削除",items:"商品",total:"合計",dietaryCheck:"食事条件の確認",removeConflict:"競合する商品またはオプションを削除してください。",noConflict:"現在のカートに既知の重大な競合はありません。",restaurantMinimum:"最低注文金額",add:"追加",met:"達成",noMinimum:"最低注文金額なし",completeRequirements:"表示された条件を解決してから決済してください。",loading:"読み込み中…",secureCheckout:"安全なデモ決済",paymentSimulation:"外部決済シミュレーション",internationalCard:"海外カード",applePayDemo:"Apple Pay デモ",presentationAvailable:"プレゼンモードで利用可能",privacy:"カード番号や個人決済情報を処理せず、実際の請求もありません。",paymentFailed:"デモ決済に失敗しました。カートは変わっていないので再試行できます。",mockConfirmed:"デモ注文確定",etaDemo:"約35分・合成予定時刻",frontDeskHandoff:"YOBI明洞ホテルのフロントに預ける",paymentSuccess:"デモ決済成功・実際の店舗や配達員には連絡していません",retry:"もう一度お試しください。以前の選択は変わっていません。"},
  "中文（简体）": {...enJourney,catalogReady:"演示目录已就绪",openCart:"打开购物车",chooseFirst:"请先选择菜单",fallbackMode:"演示连续模式",sendMessage:"发送消息",failedCheck:"未能完成核对。你的选择未更改，请重试。",demoPrompt:"我在街上看到一种红色年糕。它是什么，可以点吗？",catalogSources:"目录来源",previousMenu:"上一项",nextMenu:"下一项",syntheticMenu:"合成演示菜单",portion:"分量",sideBySide:"并排比较",bestFit:"最匹配",flavour:"风味",notVerified:"未验证",verified:"餐厅已验证",riskSignal:"风险提示",conflicting:"信息冲突",included:"已包含",blocked:"因饮食条件已禁用",unlocked:"已由你解锁，服务器仍会检查",unlock:"解锁选项",restaurantNote:"给餐厅的备注",howSay:"要怎么表达？",messageRestaurant:"给餐厅的消息",backTranslation:"回译",mildNote:"请尽量做得不辣。",handoffQuestion:"放在前台吗？",hotelFrontDesk:"酒店前台",noBellCutlery:"不按门铃·无需一次性餐具",messageCourier:"给骑手的消息",reviewTitle:"请最后确认选择。",quantity:"数量",decrease:"减少数量",increase:"增加数量",remove:"删除",items:"商品",total:"合计",dietaryCheck:"饮食条件检查",removeConflict:"请移除冲突商品或选项。",noConflict:"当前购物车没有已知的硬性冲突。",restaurantMinimum:"餐厅最低起送金额",add:"还需添加",met:"已满足",noMinimum:"无最低金额信息",completeRequirements:"请先解决标注的问题再付款。",loading:"加载中…",secureCheckout:"安全演示结账",paymentSimulation:"外部支付模拟",internationalCard:"国际银行卡",applePayDemo:"Apple Pay 演示",presentationAvailable:"演示模式可用",privacy:"不会处理卡号或个人支付数据，也不会真实扣款。",paymentFailed:"演示支付失败。购物车未改变，可以安全重试。",mockConfirmed:"演示订单已确认",etaDemo:"约35分钟·合成预计时间",frontDeskHandoff:"交给 YOBI 明洞酒店前台",paymentSuccess:"演示支付成功·未联系真实餐厅或骑手",retry:"请重试。之前的选择未更改。"},
  "中文（繁體）": {...enJourney,catalogReady:"示範目錄已就緒",openCart:"開啟購物車",chooseFirst:"請先選擇菜單",fallbackMode:"示範連續模式",sendMessage:"傳送訊息",failedCheck:"未能完成核對。你的選擇未更改，請重試。",demoPrompt:"我在街上看到一種紅色年糕。它是什麼，可以點嗎？",catalogSources:"目錄來源",previousMenu:"上一項",nextMenu:"下一項",syntheticMenu:"合成示範菜單",portion:"份量",sideBySide:"並排比較",bestFit:"最符合",flavour:"風味",notVerified:"未驗證",verified:"餐廳已驗證",riskSignal:"風險提示",conflicting:"資訊衝突",included:"已包含",blocked:"因飲食條件已停用",unlocked:"已由你解鎖，伺服器仍會檢查",unlock:"解鎖選項",restaurantNote:"給餐廳的備註",howSay:"要怎麼表達？",messageRestaurant:"給餐廳的訊息",backTranslation:"回譯",mildNote:"請盡量做得不辣。",handoffQuestion:"放在櫃檯嗎？",hotelFrontDesk:"飯店櫃檯",noBellCutlery:"不按門鈴·不需要免洗餐具",messageCourier:"給外送員的訊息",reviewTitle:"請最後確認選擇。",quantity:"數量",decrease:"減少數量",increase:"增加數量",remove:"刪除",items:"商品",total:"合計",dietaryCheck:"飲食條件檢查",removeConflict:"請移除衝突商品或選項。",noConflict:"目前購物車沒有已知的硬性衝突。",restaurantMinimum:"餐廳最低訂購金額",add:"還需加入",met:"已達成",noMinimum:"無最低金額資訊",completeRequirements:"請先解決標示的問題再付款。",loading:"載入中…",secureCheckout:"安全示範結帳",paymentSimulation:"外部付款模擬",internationalCard:"國際信用卡",applePayDemo:"Apple Pay 示範",presentationAvailable:"簡報模式可用",privacy:"不會處理卡號或個人付款資料，也不會實際扣款。",paymentFailed:"示範付款失敗。購物車未變更，可以安全重試。",mockConfirmed:"示範訂單已確認",etaDemo:"約35分鐘·合成預計時間",frontDeskHandoff:"交給 YOBI 明洞飯店櫃檯",paymentSuccess:"示範付款成功·未聯絡真實餐廳或外送員",retry:"請重試。之前的選擇未更改。"},
  Español: {...enJourney,catalogReady:"Catálogo demo listo",openCart:"Abrir carrito",chooseFirst:"Elige primero un menú",fallbackMode:"Modo de continuidad demo",sendMessage:"Enviar mensaje",failedCheck:"No pude completar la comprobación. Tus elecciones no cambiaron; inténtalo de nuevo.",demoPrompt:"Vi un plato rojo de pastel de arroz en la calle. ¿Qué es y puedo pedirlo?",catalogSources:"Fuentes del catálogo",previousMenu:"Menú anterior",nextMenu:"Menú siguiente",syntheticMenu:"Menú demo sintético",portion:"Ración",sideBySide:"Comparación",bestFit:"Mejor opción",flavour:"Sabor",notVerified:"Sin verificar",verified:"Restaurante verificado",riskSignal:"Señal de riesgo",conflicting:"Información contradictoria",included:"Incluido",blocked:"Bloqueado por tu perfil alimentario",unlocked:"Desbloqueado por ti; el servidor seguirá comprobando",unlock:"Desbloquear opción",restaurantNote:"Nota al restaurante",howSay:"¿Cómo lo decimos?",messageRestaurant:"Mensaje al restaurante",backTranslation:"Traducción inversa",mildNote:"Lo menos picante posible, por favor.",handoffQuestion:"¿Dejarlo en recepción?",hotelFrontDesk:"Recepción del hotel",noBellCutlery:"Sin timbre · sin cubiertos desechables",messageCourier:"Mensaje al repartidor",reviewTitle:"Revisa tus elecciones por última vez.",quantity:"Cantidad",decrease:"Reducir cantidad",increase:"Aumentar cantidad",remove:"Eliminar",items:"Artículos",total:"Total",dietaryCheck:"Comprobación alimentaria",removeConflict:"Elimina el artículo u opción incompatible.",noConflict:"No hay conflictos estrictos conocidos en el carrito.",restaurantMinimum:"Mínimo del restaurante",add:"añadir",met:"cumplido",noMinimum:"No hay mínimo disponible.",completeRequirements:"Completa los requisitos marcados antes de pagar.",loading:"Cargando…",secureCheckout:"Pago demo seguro",paymentSimulation:"Simulación de pago externo",internationalCard:"Tarjeta internacional",applePayDemo:"Demo de Apple Pay",presentationAvailable:"Disponible en modo presentación",privacy:"No se procesa ningún número de tarjeta, dato de pago personal ni cargo real.",paymentFailed:"El pago demo falló. El carrito no cambió y puedes reintentarlo.",mockConfirmed:"Pedido demo confirmado",etaDemo:"Unos 35 minutos · hora sintética",frontDeskHandoff:"Dejar en recepción del YOBI Myeongdong Hotel",paymentSuccess:"Pago demo correcto · no se contactó a ningún restaurante ni repartidor real",retry:"Inténtalo de nuevo. Tus elecciones anteriores no cambiaron."},
  Français: {...enJourney,catalogReady:"Catalogue démo prêt",openCart:"Ouvrir le panier",chooseFirst:"Choisissez d’abord un menu",fallbackMode:"Mode de continuité démo",sendMessage:"Envoyer le message",failedCheck:"La vérification n’a pas abouti. Vos choix sont inchangés; réessayez.",demoPrompt:"J’ai vu un plat rouge de gâteaux de riz dans la rue. Qu’est-ce que c’est et puis-je le commander ?",catalogSources:"Sources du catalogue",previousMenu:"Menu précédent",nextMenu:"Menu suivant",syntheticMenu:"Menu démo synthétique",portion:"Portion",sideBySide:"Comparaison",bestFit:"Meilleur choix",flavour:"Saveur",notVerified:"Non vérifié",verified:"Restaurant vérifié",riskSignal:"Signal de risque",conflicting:"Informations contradictoires",included:"Inclus",blocked:"Bloqué selon votre profil alimentaire",unlocked:"Déverrouillé par vous; les contrôles serveur restent actifs",unlock:"Déverrouiller",restaurantNote:"Note au restaurant",howSay:"Comment le formuler ?",messageRestaurant:"Message au restaurant",backTranslation:"Rétrotraduction",mildNote:"Le moins épicé possible, s’il vous plaît.",handoffQuestion:"Le laisser à la réception ?",hotelFrontDesk:"Réception de l’hôtel",noBellCutlery:"Sans sonnette · sans couverts jetables",messageCourier:"Message au livreur",reviewTitle:"Vérifiez une dernière fois vos choix.",quantity:"Quantité",decrease:"Réduire la quantité",increase:"Augmenter la quantité",remove:"Supprimer",items:"Articles",total:"Total",dietaryCheck:"Contrôle alimentaire",removeConflict:"Retirez l’article ou l’option incompatible.",noConflict:"Aucun conflit strict connu dans le panier.",restaurantMinimum:"Minimum du restaurant",add:"ajouter",met:"atteint",noMinimum:"Aucun minimum disponible.",completeRequirements:"Résolvez les éléments signalés avant de payer.",loading:"Chargement…",secureCheckout:"Paiement démo sécurisé",paymentSimulation:"Simulation de paiement externe",internationalCard:"Carte internationale",applePayDemo:"Démo Apple Pay",presentationAvailable:"Disponible en mode présentation",privacy:"Aucun numéro de carte, donnée de paiement personnelle ou débit réel n’est traité.",paymentFailed:"Le paiement démo a échoué. Le panier est inchangé; vous pouvez réessayer.",mockConfirmed:"Commande démo confirmée",etaDemo:"Environ 35 minutes · horaire synthétique",frontDeskHandoff:"Déposer à la réception du YOBI Myeongdong Hotel",paymentSuccess:"Paiement démo réussi · aucun restaurant ou livreur réel n’a été contacté",retry:"Réessayez. Vos choix précédents sont inchangés."},
  Deutsch: {...enJourney,catalogReady:"Demo-Katalog bereit",openCart:"Warenkorb öffnen",chooseFirst:"Zuerst ein Menü wählen",fallbackMode:"Demo-Kontinuitätsmodus",sendMessage:"Nachricht senden",failedCheck:"Die Prüfung konnte nicht abgeschlossen werden. Deine Auswahl ist unverändert; versuche es erneut.",demoPrompt:"Ich sah auf der Straße ein rotes Reiskuchengericht. Was ist das und kann ich es bestellen?",catalogSources:"Katalogquellen",previousMenu:"Vorheriges Menü",nextMenu:"Nächstes Menü",syntheticMenu:"Synthetisches Demo-Menü",portion:"Portion",sideBySide:"Vergleich",bestFit:"Beste Wahl",flavour:"Geschmack",notVerified:"Nicht verifiziert",verified:"Restaurant verifiziert",riskSignal:"Risikosignal",conflicting:"Widersprüchliche Angaben",included:"Enthalten",blocked:"Durch dein Ernährungsprofil gesperrt",unlocked:"Von dir entsperrt; Serverprüfungen bleiben aktiv",unlock:"Option entsperren",restaurantNote:"Hinweis ans Restaurant",howSay:"Wie sollen wir es sagen?",messageRestaurant:"Nachricht ans Restaurant",backTranslation:"Rückübersetzung",mildNote:"Bitte so mild wie möglich.",handoffQuestion:"An der Rezeption abgeben?",hotelFrontDesk:"Hotelrezeption",noBellCutlery:"Nicht klingeln · kein Einwegbesteck",messageCourier:"Nachricht an den Kurier",reviewTitle:"Prüfe deine Auswahl ein letztes Mal.",quantity:"Menge",decrease:"Menge verringern",increase:"Menge erhöhen",remove:"Entfernen",items:"Artikel",total:"Gesamt",dietaryCheck:"Ernährungsprüfung",removeConflict:"Entferne den widersprüchlichen Artikel oder die Option.",noConflict:"Keine bekannten harten Konflikte im Warenkorb.",restaurantMinimum:"Mindestbestellwert",add:"hinzufügen",met:"erreicht",noMinimum:"Kein Mindestwert verfügbar.",completeRequirements:"Erfülle die markierten Bedingungen vor der Zahlung.",loading:"Laden…",secureCheckout:"Sichere Demo-Zahlung",paymentSimulation:"Externe Zahlungssimulation",internationalCard:"Internationale Karte",applePayDemo:"Apple-Pay-Demo",presentationAvailable:"Im Präsentationsmodus verfügbar",privacy:"Es werden keine Kartennummern, persönlichen Zahlungsdaten oder echten Abbuchungen verarbeitet.",paymentFailed:"Die Demo-Zahlung ist fehlgeschlagen. Der Warenkorb ist unverändert; du kannst es erneut versuchen.",mockConfirmed:"Demo-Bestellung bestätigt",etaDemo:"Etwa 35 Minuten · synthetische ETA",frontDeskHandoff:"An der Rezeption des YOBI Myeongdong Hotel abgeben",paymentSuccess:"Demo-Zahlung erfolgreich · kein echtes Restaurant oder Kurier wurde kontaktiert",retry:"Versuche es erneut. Deine vorherige Auswahl ist unverändert."},
  Italiano: {...enJourney,catalogReady:"Catalogo demo pronto",openCart:"Apri carrello",chooseFirst:"Scegli prima un menu",fallbackMode:"Modalità continuità demo",sendMessage:"Invia messaggio",failedCheck:"Non ho completato il controllo. Le scelte non sono cambiate; riprova.",demoPrompt:"Ho visto in strada un piatto rosso di gnocchi di riso. Cos’è e posso ordinarlo?",catalogSources:"Fonti del catalogo",previousMenu:"Menu precedente",nextMenu:"Menu successivo",syntheticMenu:"Menu demo sintetico",portion:"Porzione",sideBySide:"Confronto",bestFit:"Migliore scelta",flavour:"Sapore",notVerified:"Non verificato",verified:"Ristorante verificato",riskSignal:"Segnale di rischio",conflicting:"Informazioni contrastanti",included:"Incluso",blocked:"Bloccato dal profilo alimentare",unlocked:"Sbloccato da te; i controlli server restano attivi",unlock:"Sblocca opzione",restaurantNote:"Nota al ristorante",howSay:"Come lo diciamo?",messageRestaurant:"Messaggio al ristorante",backTranslation:"Traduzione inversa",mildNote:"Il meno piccante possibile, per favore.",handoffQuestion:"Lasciarlo alla reception?",hotelFrontDesk:"Reception dell’hotel",noBellCutlery:"Niente campanello · niente posate usa e getta",messageCourier:"Messaggio al corriere",reviewTitle:"Controlla un’ultima volta le scelte.",quantity:"Quantità",decrease:"Riduci quantità",increase:"Aumenta quantità",remove:"Rimuovi",items:"Articoli",total:"Totale",dietaryCheck:"Controllo alimentare",removeConflict:"Rimuovi l’articolo o l’opzione in conflitto.",noConflict:"Nessun conflitto rigido noto nel carrello.",restaurantMinimum:"Minimo del ristorante",add:"aggiungi",met:"raggiunto",noMinimum:"Nessun minimo disponibile.",completeRequirements:"Risolvi i requisiti evidenziati prima di pagare.",loading:"Caricamento…",secureCheckout:"Pagamento demo sicuro",paymentSimulation:"Simulazione pagamento esterno",internationalCard:"Carta internazionale",applePayDemo:"Demo Apple Pay",presentationAvailable:"Disponibile in modalità presentazione",privacy:"Non vengono elaborati numero di carta, dati personali di pagamento o addebiti reali.",paymentFailed:"Il pagamento demo non è riuscito. Il carrello è invariato; puoi riprovare.",mockConfirmed:"Ordine demo confermato",etaDemo:"Circa 35 minuti · orario sintetico",frontDeskHandoff:"Lasciare alla reception dello YOBI Myeongdong Hotel",paymentSuccess:"Pagamento demo riuscito · nessun ristorante o corriere reale contattato",retry:"Riprova. Le scelte precedenti sono invariate."},
  Português: {...enJourney,catalogReady:"Catálogo demo pronto",openCart:"Abrir carrinho",chooseFirst:"Escolha primeiro um menu",fallbackMode:"Modo de continuidade demo",sendMessage:"Enviar mensagem",failedCheck:"Não consegui concluir a verificação. Suas escolhas não mudaram; tente novamente.",demoPrompt:"Vi na rua um prato vermelho de bolinho de arroz. O que é e posso pedir?",catalogSources:"Fontes do catálogo",previousMenu:"Menu anterior",nextMenu:"Próximo menu",syntheticMenu:"Menu demo sintético",portion:"Porção",sideBySide:"Comparação",bestFit:"Melhor opção",flavour:"Sabor",notVerified:"Não verificado",verified:"Restaurante verificado",riskSignal:"Sinal de risco",conflicting:"Informações conflitantes",included:"Incluído",blocked:"Bloqueado pelo seu perfil alimentar",unlocked:"Desbloqueado por você; as verificações do servidor continuam",unlock:"Desbloquear opção",restaurantNote:"Nota ao restaurante",howSay:"Como devemos dizer?",messageRestaurant:"Mensagem ao restaurante",backTranslation:"Retrotradução",mildNote:"O menos picante possível, por favor.",handoffQuestion:"Deixar na recepção?",hotelFrontDesk:"Recepção do hotel",noBellCutlery:"Sem campainha · sem talheres descartáveis",messageCourier:"Mensagem ao entregador",reviewTitle:"Revise suas escolhas uma última vez.",quantity:"Quantidade",decrease:"Diminuir quantidade",increase:"Aumentar quantidade",remove:"Remover",items:"Itens",total:"Total",dietaryCheck:"Verificação alimentar",removeConflict:"Remova o item ou opção conflitante.",noConflict:"Nenhum conflito rígido conhecido no carrinho.",restaurantMinimum:"Mínimo do restaurante",add:"adicionar",met:"atingido",noMinimum:"Nenhum mínimo disponível.",completeRequirements:"Resolva os requisitos destacados antes de pagar.",loading:"Carregando…",secureCheckout:"Pagamento demo seguro",paymentSimulation:"Simulação de pagamento externo",internationalCard:"Cartão internacional",applePayDemo:"Demo do Apple Pay",presentationAvailable:"Disponível no modo apresentação",privacy:"Nenhum número de cartão, dado pessoal de pagamento ou cobrança real é processado.",paymentFailed:"O pagamento demo falhou. O carrinho não mudou; você pode tentar novamente.",mockConfirmed:"Pedido demo confirmado",etaDemo:"Cerca de 35 minutos · horário sintético",frontDeskHandoff:"Deixar na recepção do YOBI Myeongdong Hotel",paymentSuccess:"Pagamento demo concluído · nenhum restaurante ou entregador real foi contatado",retry:"Tente novamente. Suas escolhas anteriores não mudaram."},
  "ไทย": {...enJourney,catalogReady:"แคตตาล็อกเดโมพร้อม",openCart:"เปิดรถเข็น",chooseFirst:"เลือกเมนูก่อน",fallbackMode:"โหมดเดโมต่อเนื่อง",sendMessage:"ส่งข้อความ",failedCheck:"ตรวจสอบไม่สำเร็จ ตัวเลือกเดิมไม่เปลี่ยน โปรดลองอีกครั้ง",demoPrompt:"ฉันเห็นต็อกสีแดงข้างถนน มันคืออะไรและสั่งได้ไหม?",catalogSources:"แหล่งแคตตาล็อก",previousMenu:"เมนูก่อนหน้า",nextMenu:"เมนูถัดไป",syntheticMenu:"เมนูเดโมสังเคราะห์",portion:"ปริมาณ",sideBySide:"เปรียบเทียบ",bestFit:"เหมาะที่สุด",flavour:"รสชาติ",notVerified:"ยังไม่ยืนยัน",verified:"ร้านยืนยันแล้ว",riskSignal:"สัญญาณความเสี่ยง",conflicting:"ข้อมูลขัดแย้ง",included:"รวมแล้ว",blocked:"ปิดใช้งานตามข้อมูลการกิน",unlocked:"คุณปลดล็อกแล้ว การตรวจสอบเซิร์ฟเวอร์ยังทำงาน",unlock:"ปลดล็อกตัวเลือก",restaurantNote:"หมายเหตุถึงร้าน",howSay:"ควรบอกอย่างไร?",messageRestaurant:"ข้อความถึงร้าน",backTranslation:"แปลกลับ",mildNote:"กรุณาทำให้เผ็ดน้อยที่สุด",handoffQuestion:"ฝากไว้ที่เคาน์เตอร์ไหม?",hotelFrontDesk:"เคาน์เตอร์โรงแรม",noBellCutlery:"ไม่กดกริ่ง · ไม่รับช้อนส้อมใช้แล้วทิ้ง",messageCourier:"ข้อความถึงผู้ส่ง",reviewTitle:"ตรวจสอบตัวเลือกครั้งสุดท้าย",quantity:"จำนวน",decrease:"ลดจำนวน",increase:"เพิ่มจำนวน",remove:"ลบ",items:"รายการ",total:"รวม",dietaryCheck:"ตรวจสอบข้อจำกัดอาหาร",removeConflict:"นำรายการหรือตัวเลือกที่ขัดแย้งออก",noConflict:"ไม่พบข้อขัดแย้งที่ทราบในรถเข็น",restaurantMinimum:"ยอดขั้นต่ำของร้าน",add:"เพิ่ม",met:"ครบแล้ว",noMinimum:"ไม่มีข้อมูลยอดขั้นต่ำ",completeRequirements:"แก้ไขเงื่อนไขที่ระบุก่อนชำระเงิน",loading:"กำลังโหลด…",secureCheckout:"ชำระเงินเดโมแบบปลอดภัย",paymentSimulation:"จำลองการชำระเงินภายนอก",internationalCard:"บัตรต่างประเทศ",applePayDemo:"Apple Pay เดโม",presentationAvailable:"ใช้ได้ในโหมดนำเสนอ",privacy:"ไม่มีการประมวลผลเลขบัตร ข้อมูลชำระเงินส่วนตัว หรือการเรียกเก็บเงินจริง",paymentFailed:"การชำระเงินเดโมล้มเหลว รถเข็นไม่เปลี่ยนและลองใหม่ได้",mockConfirmed:"ยืนยันคำสั่งซื้อเดโม",etaDemo:"ประมาณ 35 นาที · เวลาสังเคราะห์",frontDeskHandoff:"ฝากที่เคาน์เตอร์ YOBI Myeongdong Hotel",paymentSuccess:"ชำระเงินเดโมสำเร็จ · ไม่มีการติดต่อร้านหรือผู้ส่งจริง",retry:"โปรดลองอีกครั้ง ตัวเลือกก่อนหน้าไม่เปลี่ยน"},
  "Tiếng Việt": {...enJourney,catalogReady:"Danh mục demo đã sẵn sàng",openCart:"Mở giỏ hàng",chooseFirst:"Hãy chọn món trước",fallbackMode:"Chế độ duy trì demo",sendMessage:"Gửi tin nhắn",failedCheck:"Không thể hoàn tất kiểm tra. Lựa chọn không thay đổi; hãy thử lại.",demoPrompt:"Tôi thấy món bánh gạo đỏ trên phố. Đó là món gì và tôi có thể đặt không?",catalogSources:"Nguồn danh mục",previousMenu:"Món trước",nextMenu:"Món sau",syntheticMenu:"Món demo tổng hợp",portion:"Khẩu phần",sideBySide:"So sánh",bestFit:"Phù hợp nhất",flavour:"Hương vị",notVerified:"Chưa xác minh",verified:"Nhà hàng đã xác minh",riskSignal:"Cảnh báo rủi ro",conflicting:"Thông tin mâu thuẫn",included:"Đã gồm",blocked:"Bị khóa theo hồ sơ ăn uống",unlocked:"Bạn đã mở khóa; máy chủ vẫn kiểm tra",unlock:"Mở khóa tùy chọn",restaurantNote:"Ghi chú cho nhà hàng",howSay:"Nên nói thế nào?",messageRestaurant:"Tin nhắn cho nhà hàng",backTranslation:"Bản dịch ngược",mildNote:"Vui lòng làm ít cay nhất có thể.",handoffQuestion:"Để ở quầy lễ tân?",hotelFrontDesk:"Quầy lễ tân khách sạn",noBellCutlery:"Không bấm chuông · không dụng cụ dùng một lần",messageCourier:"Tin nhắn cho người giao",reviewTitle:"Kiểm tra lựa chọn lần cuối.",quantity:"Số lượng",decrease:"Giảm số lượng",increase:"Tăng số lượng",remove:"Xóa",items:"Món",total:"Tổng",dietaryCheck:"Kiểm tra ăn uống",removeConflict:"Xóa món hoặc tùy chọn xung đột.",noConflict:"Không có xung đột cứng đã biết trong giỏ.",restaurantMinimum:"Tối thiểu của nhà hàng",add:"thêm",met:"đã đạt",noMinimum:"Không có mức tối thiểu.",completeRequirements:"Hoàn tất các yêu cầu được đánh dấu trước khi thanh toán.",loading:"Đang tải…",secureCheckout:"Thanh toán demo an toàn",paymentSimulation:"Mô phỏng thanh toán ngoài",internationalCard:"Thẻ quốc tế",applePayDemo:"Apple Pay demo",presentationAvailable:"Có trong chế độ trình chiếu",privacy:"Không xử lý số thẻ, dữ liệu thanh toán cá nhân hay khoản phí thật.",paymentFailed:"Thanh toán demo thất bại. Giỏ hàng không đổi; bạn có thể thử lại.",mockConfirmed:"Đã xác nhận đơn demo",etaDemo:"Khoảng 35 phút · thời gian tổng hợp",frontDeskHandoff:"Để tại quầy lễ tân YOBI Myeongdong Hotel",paymentSuccess:"Thanh toán demo thành công · không liên hệ nhà hàng hay người giao thật",retry:"Hãy thử lại. Lựa chọn trước không thay đổi."},
  "Bahasa Indonesia": {...enJourney,catalogReady:"Katalog demo siap",openCart:"Buka keranjang",chooseFirst:"Pilih menu terlebih dahulu",fallbackMode:"Mode kelanjutan demo",sendMessage:"Kirim pesan",failedCheck:"Pemeriksaan tidak selesai. Pilihan Anda tidak berubah; coba lagi.",demoPrompt:"Saya melihat hidangan kue beras merah di jalan. Apa itu dan bisakah saya memesannya?",catalogSources:"Sumber katalog",previousMenu:"Menu sebelumnya",nextMenu:"Menu berikutnya",syntheticMenu:"Menu demo sintetis",portion:"Porsi",sideBySide:"Perbandingan",bestFit:"Paling sesuai",flavour:"Rasa",notVerified:"Belum diverifikasi",verified:"Restoran terverifikasi",riskSignal:"Sinyal risiko",conflicting:"Informasi bertentangan",included:"Termasuk",blocked:"Dikunci berdasarkan profil diet",unlocked:"Anda membuka kunci; pemeriksaan server tetap berlaku",unlock:"Buka kunci opsi",restaurantNote:"Catatan untuk restoran",howSay:"Bagaimana menyampaikannya?",messageRestaurant:"Pesan untuk restoran",backTranslation:"Terjemahan balik",mildNote:"Tolong buat sepedas mungkin rendah.",handoffQuestion:"Titipkan di resepsionis?",hotelFrontDesk:"Resepsionis hotel",noBellCutlery:"Tanpa bel · tanpa alat makan sekali pakai",messageCourier:"Pesan untuk kurir",reviewTitle:"Periksa pilihan Anda sekali lagi.",quantity:"Jumlah",decrease:"Kurangi jumlah",increase:"Tambah jumlah",remove:"Hapus",items:"Item",total:"Total",dietaryCheck:"Pemeriksaan diet",removeConflict:"Hapus item atau opsi yang bertentangan.",noConflict:"Tidak ada konflik keras yang diketahui di keranjang.",restaurantMinimum:"Minimum restoran",add:"tambah",met:"terpenuhi",noMinimum:"Tidak ada minimum.",completeRequirements:"Selesaikan persyaratan yang ditandai sebelum membayar.",loading:"Memuat…",secureCheckout:"Pembayaran demo aman",paymentSimulation:"Simulasi pembayaran eksternal",internationalCard:"Kartu internasional",applePayDemo:"Demo Apple Pay",presentationAvailable:"Tersedia dalam mode presentasi",privacy:"Nomor kartu, data pembayaran pribadi, dan tagihan nyata tidak diproses.",paymentFailed:"Pembayaran demo gagal. Keranjang tidak berubah; Anda dapat mencoba lagi.",mockConfirmed:"Pesanan demo dikonfirmasi",etaDemo:"Sekitar 35 menit · ETA sintetis",frontDeskHandoff:"Titipkan di resepsionis YOBI Myeongdong Hotel",paymentSuccess:"Pembayaran demo berhasil · tidak ada restoran atau kurir nyata yang dihubungi",retry:"Coba lagi. Pilihan sebelumnya tidak berubah."},
  "العربية": {...enJourney,catalogReady:"الكتالوج التجريبي جاهز",openCart:"فتح السلة",chooseFirst:"اختر قائمة أولًا",fallbackMode:"وضع استمرارية العرض",sendMessage:"إرسال الرسالة",failedCheck:"تعذر إكمال التحقق. لم تتغير اختياراتك؛ حاول مجددًا.",demoPrompt:"رأيت طبق كعك أرز أحمر في الشارع. ما هو وهل يمكنني طلبه؟",catalogSources:"مصادر الكتالوج",previousMenu:"القائمة السابقة",nextMenu:"القائمة التالية",syntheticMenu:"قائمة تجريبية اصطناعية",portion:"الكمية",sideBySide:"مقارنة",bestFit:"الأنسب",flavour:"النكهة",notVerified:"غير متحقق",verified:"المطعم متحقق منه",riskSignal:"إشارة خطر",conflicting:"معلومات متعارضة",included:"مشمول",blocked:"محظور وفق ملفك الغذائي",unlocked:"فتحته أنت؛ فحوص الخادم مستمرة",unlock:"فتح الخيار",restaurantNote:"ملاحظة للمطعم",howSay:"كيف نصوغها؟",messageRestaurant:"رسالة للمطعم",backTranslation:"الترجمة العكسية",mildNote:"يرجى جعله غير حار قدر الإمكان.",handoffQuestion:"نتركه عند الاستقبال؟",hotelFrontDesk:"استقبال الفندق",noBellCutlery:"بدون جرس · بدون أدوات أحادية الاستخدام",messageCourier:"رسالة للمندوب",reviewTitle:"راجع اختياراتك للمرة الأخيرة.",quantity:"الكمية",decrease:"تقليل الكمية",increase:"زيادة الكمية",remove:"حذف",items:"العناصر",total:"الإجمالي",dietaryCheck:"فحص القيود الغذائية",removeConflict:"أزل العنصر أو الخيار المتعارض.",noConflict:"لا يوجد تعارض صارم معروف في السلة.",restaurantMinimum:"الحد الأدنى للمطعم",add:"أضف",met:"مستوفى",noMinimum:"لا يوجد حد أدنى.",completeRequirements:"أكمل المتطلبات المحددة قبل الدفع.",loading:"جارٍ التحميل…",secureCheckout:"دفع تجريبي آمن",paymentSimulation:"محاكاة دفع خارجية",internationalCard:"بطاقة دولية",applePayDemo:"عرض Apple Pay",presentationAvailable:"متاح في وضع العرض",privacy:"لا تتم معالجة رقم بطاقة أو بيانات دفع شخصية أو رسوم حقيقية.",paymentFailed:"فشل الدفع التجريبي. لم تتغير السلة ويمكنك المحاولة مجددًا.",mockConfirmed:"تم تأكيد الطلب التجريبي",etaDemo:"نحو 35 دقيقة · وقت اصطناعي",frontDeskHandoff:"اتركه عند استقبال فندق YOBI Myeongdong",paymentSuccess:"نجح الدفع التجريبي · لم يتم الاتصال بمطعم أو مندوب حقيقي",retry:"حاول مجددًا. لم تتغير اختياراتك السابقة."},
  "हिन्दी": {...enJourney,catalogReady:"डेमो कैटलॉग तैयार",openCart:"कार्ट खोलें",chooseFirst:"पहले मेनू चुनें",fallbackMode:"डेमो निरंतरता मोड",sendMessage:"संदेश भेजें",failedCheck:"जाँच पूरी नहीं हो सकी। आपके चुनाव नहीं बदले; फिर कोशिश करें।",demoPrompt:"मैंने सड़क पर लाल राइस केक व्यंजन देखा। यह क्या है और क्या मैं इसे मंगा सकता/सकती हूँ?",catalogSources:"कैटलॉग स्रोत",previousMenu:"पिछला मेनू",nextMenu:"अगला मेनू",syntheticMenu:"सिंथेटिक डेमो मेनू",portion:"मात्रा",sideBySide:"तुलना",bestFit:"सबसे उपयुक्त",flavour:"स्वाद",notVerified:"सत्यापित नहीं",verified:"रेस्तरां सत्यापित",riskSignal:"जोखिम संकेत",conflicting:"विरोधी जानकारी",included:"शामिल",blocked:"आपकी भोजन प्रोफ़ाइल के कारण बंद",unlocked:"आपने खोला; सर्वर जाँच जारी रहेगी",unlock:"विकल्प खोलें",restaurantNote:"रेस्तरां के लिए नोट",howSay:"इसे कैसे कहें?",messageRestaurant:"रेस्तरां को संदेश",backTranslation:"वापस अनुवाद",mildNote:"कृपया इसे जितना हो सके कम तीखा रखें।",handoffQuestion:"फ्रंट डेस्क पर छोड़ें?",hotelFrontDesk:"होटल फ्रंट डेस्क",noBellCutlery:"घंटी नहीं · डिस्पोजेबल कटलरी नहीं",messageCourier:"कूरियर को संदेश",reviewTitle:"अपने चुनाव आखिरी बार जाँचें।",quantity:"मात्रा",decrease:"मात्रा घटाएँ",increase:"मात्रा बढ़ाएँ",remove:"हटाएँ",items:"आइटम",total:"कुल",dietaryCheck:"भोजन जाँच",removeConflict:"टकराने वाला आइटम या विकल्प हटाएँ।",noConflict:"कार्ट में कोई ज्ञात सख्त टकराव नहीं।",restaurantMinimum:"रेस्तरां न्यूनतम",add:"जोड़ें",met:"पूरा",noMinimum:"न्यूनतम उपलब्ध नहीं।",completeRequirements:"भुगतान से पहले चिह्नित आवश्यकताएँ पूरी करें।",loading:"लोड हो रहा है…",secureCheckout:"सुरक्षित डेमो भुगतान",paymentSimulation:"बाहरी भुगतान सिमुलेशन",internationalCard:"अंतरराष्ट्रीय कार्ड",applePayDemo:"Apple Pay डेमो",presentationAvailable:"प्रेज़ेंटेशन मोड में उपलब्ध",privacy:"कार्ड नंबर, निजी भुगतान डेटा या वास्तविक शुल्क संसाधित नहीं होता।",paymentFailed:"डेमो भुगतान विफल। कार्ट नहीं बदला; आप फिर कोशिश कर सकते हैं।",mockConfirmed:"डेमो ऑर्डर पक्का",etaDemo:"लगभग 35 मिनट · सिंथेटिक समय",frontDeskHandoff:"YOBI Myeongdong Hotel फ्रंट डेस्क पर छोड़ें",paymentSuccess:"डेमो भुगतान सफल · किसी असली रेस्तरां या कूरियर से संपर्क नहीं हुआ",retry:"फिर कोशिश करें। आपके पिछले चुनाव नहीं बदले।"},
  "Русский": {...enJourney,catalogReady:"Демо-каталог готов",openCart:"Открыть корзину",chooseFirst:"Сначала выберите меню",fallbackMode:"Режим продолжения демо",sendMessage:"Отправить сообщение",failedCheck:"Не удалось завершить проверку. Ваш выбор не изменён; попробуйте снова.",demoPrompt:"Я увидел(а) на улице красное блюдо из рисовых клёцек. Что это и можно ли его заказать?",catalogSources:"Источники каталога",previousMenu:"Предыдущее меню",nextMenu:"Следующее меню",syntheticMenu:"Синтетическое демо-меню",portion:"Порция",sideBySide:"Сравнение",bestFit:"Лучший вариант",flavour:"Вкус",notVerified:"Не проверено",verified:"Ресторан проверен",riskSignal:"Сигнал риска",conflicting:"Противоречивые сведения",included:"Включено",blocked:"Заблокировано по пищевому профилю",unlocked:"Разблокировано вами; серверные проверки продолжаются",unlock:"Разблокировать",restaurantNote:"Примечание ресторану",howSay:"Как это сказать?",messageRestaurant:"Сообщение ресторану",backTranslation:"Обратный перевод",mildNote:"Пожалуйста, сделайте как можно менее острым.",handoffQuestion:"Оставить на стойке регистрации?",hotelFrontDesk:"Стойка регистрации",noBellCutlery:"Не звонить · без одноразовых приборов",messageCourier:"Сообщение курьеру",reviewTitle:"Проверьте выбор в последний раз.",quantity:"Количество",decrease:"Уменьшить количество",increase:"Увеличить количество",remove:"Удалить",items:"Товары",total:"Итого",dietaryCheck:"Проверка ограничений",removeConflict:"Удалите конфликтующий товар или опцию.",noConflict:"В корзине нет известных жёстких конфликтов.",restaurantMinimum:"Минимум ресторана",add:"добавить",met:"достигнут",noMinimum:"Минимум не указан.",completeRequirements:"Выполните отмеченные требования перед оплатой.",loading:"Загрузка…",secureCheckout:"Безопасная демо-оплата",paymentSimulation:"Симуляция внешнего платежа",internationalCard:"Международная карта",applePayDemo:"Демо Apple Pay",presentationAvailable:"Доступно в режиме презентации",privacy:"Номер карты, личные платёжные данные и реальные списания не обрабатываются.",paymentFailed:"Демо-платёж не прошёл. Корзина не изменилась; можно повторить.",mockConfirmed:"Демо-заказ подтверждён",etaDemo:"Около 35 минут · синтетическое время",frontDeskHandoff:"Оставить на стойке YOBI Myeongdong Hotel",paymentSuccess:"Демо-платёж успешен · настоящий ресторан или курьер не привлекались",retry:"Попробуйте снова. Предыдущий выбор не изменён."},
};

export function getExtendedCopy(language: SupportedLanguage) {
  const effectiveLanguage = asEffectiveLanguage(language);
  const selectionCopy = { ...selectionBase[effectiveLanguage], religionValues };
  const journeyCopy = { ...journeyPacks[effectiveLanguage] };

  if (effectiveLanguage === "English") {
    Object.assign(selectionCopy, {
      useDemoImage: "Use the sample booking image",
      syntheticPlace: "saved place",
      demoImageError: "The address could not be checked. Try the hotel search.",
    });
    Object.assign(journeyCopy, {
      catalogReady: "Catalog ready",
      fallbackMode: "Continue with available menus",
      syntheticMenu: "Menu",
      secureCheckout: "Secure checkout",
      paymentSimulation: "Payment",
      applePayDemo: "Apple Pay",
      presentationAvailable: "Available",
      privacy: "Review the order details before continuing.",
      paymentFailed: "Payment failed. Your cart is unchanged, so you can retry safely.",
      mockConfirmed: "Order confirmed",
      etaDemo: "About 35 minutes",
      paymentSuccess: "Payment successful",
    });
  } else if (effectiveLanguage === "한국어") {
    Object.assign(selectionCopy, {
      useDemoImage: "예약 예시 이미지 사용",
      syntheticPlace: "저장된 장소",
      demoImageError: "주소를 확인하지 못했어요. 호텔 검색을 이용해 주세요.",
    });
    Object.assign(journeyCopy, {
      catalogReady: "메뉴 준비 완료",
      fallbackMode: "이용 가능한 메뉴로 계속",
      syntheticMenu: "메뉴",
      secureCheckout: "안전한 결제",
      paymentSimulation: "결제",
      applePayDemo: "Apple Pay",
      presentationAvailable: "사용 가능",
      privacy: "계속하기 전 주문 정보를 확인해 주세요.",
      paymentFailed: "결제에 실패했어요. 장바구니는 유지되므로 다시 시도할 수 있어요.",
      mockConfirmed: "주문 확정",
      etaDemo: "약 35분",
      paymentSuccess: "결제가 완료됐어요.",
    });
  } else {
    Object.assign(selectionCopy, {
      useDemoImage: "予約イメージ例を使う",
      syntheticPlace: "保存済みの場所",
      demoImageError: "住所を確認できませんでした。ホテル検索をお試しください。",
    });
    Object.assign(journeyCopy, {
      catalogReady: "メニューの準備完了",
      fallbackMode: "利用可能なメニューで続ける",
      syntheticMenu: "メニュー",
      secureCheckout: "安全な決済",
      paymentSimulation: "決済",
      applePayDemo: "Apple Pay",
      presentationAvailable: "利用可能",
      privacy: "続ける前に注文内容を確認してください。",
      paymentFailed: "決済に失敗しました。カートは変わっていないため再試行できます。",
      mockConfirmed: "注文確定",
      etaDemo: "約35分",
      paymentSuccess: "決済が完了しました。",
    });
  }
  return {
    selectionCopy,
    journeyCopy,
  };
}
