import { useEffect } from "react";
import { asSupportedLanguage, LANGUAGE_META, type SupportedLanguage } from "./locale";
import { useSessionStore } from "../stores/session";
import { getExtendedCopy } from "./extendedI18n";
import { getChatMenuCopy } from "./chatMenuI18n";

export interface UiCopy {
  buddy: string; ready: string; checking: string; hello: string; you: string; ask: string;
  placeholder: string; demoQuestion: string; orderBuilder: string; close: string;
  options: string; delivery: string; review: string; spice: string; chooseMenu: string;
  whyMatch: string; evidence: string; addCart: string; added: string; moreQuestion: string;
  moreDescription: string; yesMore: string; noDelivery: string; moreFrom: string;
  swipeMore: string; noMore: string; confirmDelivery: string; finalReview: string;
  readyCheckout: string; proceedPayment: string; demoPayment: string; paymentTitle: string;
  pay: string; simulateFailure: string; orderConfirmed: string; arrival: string;
  handoff: string; anotherOrder: string; conversation: string;
}

export interface ProfileCopy {
  step: string; title: string; age: string; religion: string; dietary: string; vegan: string;
  allergies: string; severity: string; spice: string; favourites: string; address: string;
  required: string; hotel: string; image: string; road: string; consent: string; check: string;
  changeLocale: string;
}

export interface DynamicCopy {
  fallbackResult: string; menuMatches: string; catalogDescription: string;
  matchReason: string; riskUnknown: string; evidenceDescription: string;
}

const en: UiCopy = {
  buddy: "Your Korean food buddy", ready: "Your delivery context is ready", checking: "Checking menu details…",
  hello: "Hi, I’m YOBI. Tell me what you remember about the food—or how you want tonight’s meal to feel. I’ll translate that into grounded demo choices.",
  you: "You", ask: "Ask YOBI", placeholder: "I saw a red rice cake dish on the street…", demoQuestion: "Try the demo question",
  orderBuilder: "Order builder", close: "Close", options: "options", delivery: "delivery", review: "review", spice: "Spice level",
  chooseMenu: "Choose this menu", whyMatch: "Why this match", evidence: "Evidence sources", addCart: "Add to mock cart",
  added: "Added to mock cart", moreQuestion: "Would you like anything else from this restaurant?", moreDescription: "Browse its remaining compatible menus, or continue to delivery.",
  yesMore: "Yes, show more menus", noDelivery: "No, continue to delivery", moreFrom: "More from this restaurant", swipeMore: "Swipe through compatible menus from the same restaurant.",
  noMore: "No more items — continue to delivery", confirmDelivery: "Confirm delivery details", finalReview: "Final review", readyCheckout: "Ready to checkout",
  proceedPayment: "Proceed to payment", demoPayment: "Demo payment — no real charge", paymentTitle: "Complete your demo order", pay: "Pay", simulateFailure: "Simulate failure",
  orderConfirmed: "Your first K-food order is in.", arrival: "Estimated arrival", handoff: "Handoff", anotherOrder: "Start another order", conversation: "View conversation",
};

const packs: Record<SupportedLanguage, UiCopy> = {
  English: en,
  "한국어": { buddy:"당신의 한국 음식 친구",ready:"배달 정보가 준비됐어요",checking:"메뉴 정보를 확인하고 있어요…",hello:"안녕하세요, YOBI예요. 기억나는 음식이나 오늘 먹고 싶은 느낌을 알려 주세요. 근거가 확인된 데모 메뉴로 찾아드릴게요.",you:"나",ask:"YOBI에게 묻기",placeholder:"길거리에서 빨간 떡 요리를 봤어요…",demoQuestion:"데모 질문 사용하기",orderBuilder:"주문 만들기",close:"닫기",options:"옵션",delivery:"배달",review:"검토",spice:"맵기 단계",chooseMenu:"이 메뉴 선택",whyMatch:"추천 이유",evidence:"근거 출처",addCart:"데모 장바구니에 담기",added:"데모 장바구니에 담았어요",moreQuestion:"이 가게에서 메뉴를 더 고를까요?",moreDescription:"같은 가게의 조건에 맞는 다른 메뉴를 보거나 배달 단계로 이동하세요.",yesMore:"네, 다른 메뉴 보기",noDelivery:"아니요, 배달 단계로",moreFrom:"이 가게의 다른 메뉴",swipeMore:"같은 가게의 조건에 맞는 메뉴를 옆으로 넘겨 보세요.",noMore:"그만 담고 배달 단계로",confirmDelivery:"배달 정보 확인",finalReview:"최종 검토",readyCheckout:"결제 준비 상태",proceedPayment:"결제로 이동",demoPayment:"데모 결제 · 실제 결제 없음",paymentTitle:"데모 주문 결제하기",pay:"결제",simulateFailure:"결제 실패 시뮬레이션",orderConfirmed:"첫 한국 음식 주문이 접수됐어요.",arrival:"예상 도착",handoff:"전달 방법",anotherOrder:"새 주문 시작",conversation:"대화 보기"},
  "日本語": { buddy:"韓国料理の相棒",ready:"配達情報の準備ができました",checking:"メニューを確認中…",hello:"こんにちは、YOBIです。覚えている料理や今夜食べたい気分を教えてください。根拠のあるデモ候補をご案内します。",you:"あなた",ask:"YOBIに聞く",placeholder:"街で赤い餅料理を見ました…",demoQuestion:"デモ質問を試す",orderBuilder:"注文を作る",close:"閉じる",options:"オプション",delivery:"配達",review:"確認",spice:"辛さレベル",chooseMenu:"このメニューを選ぶ",whyMatch:"おすすめの理由",evidence:"根拠の出典",addCart:"デモカートに追加",added:"デモカートに追加しました",moreQuestion:"この店でほかにも選びますか？",moreDescription:"同じ店の条件に合うメニューを見るか、配達へ進みます。",yesMore:"はい、もっと見る",noDelivery:"いいえ、配達へ",moreFrom:"この店のほかのメニュー",swipeMore:"同じ店のメニューをスワイプして確認できます。",noMore:"追加せず配達へ",confirmDelivery:"配達情報を確認",finalReview:"最終確認",readyCheckout:"決済準備",proceedPayment:"決済へ進む",demoPayment:"デモ決済・実際の請求なし",paymentTitle:"デモ注文を完了",pay:"支払う",simulateFailure:"失敗を試す",orderConfirmed:"初めての韓国料理を注文しました。",arrival:"到着予定",handoff:"受け渡し",anotherOrder:"別の注文を始める",conversation:"会話を見る"},
  "中文（简体）": { buddy:"你的韩国美食伙伴",ready:"配送信息已准备好",checking:"正在核对菜单…",hello:"你好，我是 YOBI。告诉我你记得的食物，或今晚想吃什么感觉，我会提供有依据的演示推荐。",you:"你",ask:"问 YOBI",placeholder:"我在街上看到一种红色年糕…",demoQuestion:"试试演示问题",orderBuilder:"创建订单",close:"关闭",options:"选项",delivery:"配送",review:"确认",spice:"辣度等级",chooseMenu:"选择此菜单",whyMatch:"推荐理由",evidence:"依据来源",addCart:"加入演示购物车",added:"已加入演示购物车",moreQuestion:"还想在这家店点别的吗？",moreDescription:"查看同店其他符合条件的菜单，或继续配送。",yesMore:"是的，查看更多",noDelivery:"不了，继续配送",moreFrom:"这家店的更多菜单",swipeMore:"左右滑动查看同店菜单。",noMore:"不再添加，继续配送",confirmDelivery:"确认配送信息",finalReview:"最终确认",readyCheckout:"可以结账",proceedPayment:"前往付款",demoPayment:"演示付款，不会真实扣款",paymentTitle:"完成演示订单",pay:"支付",simulateFailure:"模拟失败",orderConfirmed:"你的第一份韩国美食订单已提交。",arrival:"预计送达",handoff:"交付方式",anotherOrder:"开始新订单",conversation:"查看对话"},
  "中文（繁體）": { buddy:"你的韓國美食夥伴",ready:"配送資訊已準備好",checking:"正在核對菜單…",hello:"你好，我是 YOBI。告訴我你記得的食物，或今晚想吃的感覺，我會提供有依據的示範推薦。",you:"你",ask:"問 YOBI",placeholder:"我在街上看到一種紅色年糕…",demoQuestion:"試試示範問題",orderBuilder:"建立訂單",close:"關閉",options:"選項",delivery:"配送",review:"確認",spice:"辣度等級",chooseMenu:"選擇此菜單",whyMatch:"推薦理由",evidence:"依據來源",addCart:"加入示範購物車",added:"已加入示範購物車",moreQuestion:"還想在這家店點別的嗎？",moreDescription:"查看同店其他符合條件的菜單，或繼續配送。",yesMore:"是，查看更多",noDelivery:"不了，繼續配送",moreFrom:"這家店的更多菜單",swipeMore:"左右滑動查看同店菜單。",noMore:"不再加入，繼續配送",confirmDelivery:"確認配送資訊",finalReview:"最終確認",readyCheckout:"可以結帳",proceedPayment:"前往付款",demoPayment:"示範付款，不會真實扣款",paymentTitle:"完成示範訂單",pay:"付款",simulateFailure:"模擬失敗",orderConfirmed:"你的第一份韓國美食訂單已送出。",arrival:"預計送達",handoff:"交付方式",anotherOrder:"開始新訂單",conversation:"查看對話"},
  Español: { buddy:"Tu compañero de comida coreana",ready:"Tu contexto de entrega está listo",checking:"Comprobando el menú…",hello:"Hola, soy YOBI. Cuéntame qué comida recuerdas o qué te apetece esta noche y te mostraré opciones de demostración con evidencia.",you:"Tú",ask:"Pregunta a YOBI",placeholder:"Vi un plato rojo de pastel de arroz…",demoQuestion:"Probar la pregunta de demo",orderBuilder:"Crear pedido",close:"Cerrar",options:"opciones",delivery:"entrega",review:"revisión",spice:"Nivel de picante",chooseMenu:"Elegir este menú",whyMatch:"Por qué encaja",evidence:"Fuentes",addCart:"Añadir al carrito demo",added:"Añadido al carrito demo",moreQuestion:"¿Quieres algo más de este restaurante?",moreDescription:"Explora otros menús compatibles del mismo local o continúa con la entrega.",yesMore:"Sí, ver más menús",noDelivery:"No, continuar a entrega",moreFrom:"Más de este restaurante",swipeMore:"Desliza para ver menús compatibles del mismo restaurante.",noMore:"Nada más; continuar a entrega",confirmDelivery:"Confirmar entrega",finalReview:"Revisión final",readyCheckout:"Listo para pagar",proceedPayment:"Ir al pago",demoPayment:"Pago demo, sin cargo real",paymentTitle:"Completa tu pedido demo",pay:"Pagar",simulateFailure:"Simular fallo",orderConfirmed:"Tu primer pedido de comida coreana está en marcha.",arrival:"Llegada estimada",handoff:"Entrega",anotherOrder:"Iniciar otro pedido",conversation:"Ver conversación"},
  Français: { buddy:"Votre compagnon de cuisine coréenne",ready:"Votre contexte de livraison est prêt",checking:"Vérification du menu…",hello:"Bonjour, je suis YOBI. Décrivez le plat dont vous vous souvenez ou votre envie du soir; je proposerai des choix de démonstration étayés.",you:"Vous",ask:"Demander à YOBI",placeholder:"J’ai vu un plat rouge de gâteaux de riz…",demoQuestion:"Essayer la question démo",orderBuilder:"Composer la commande",close:"Fermer",options:"options",delivery:"livraison",review:"vérification",spice:"Niveau de piquant",chooseMenu:"Choisir ce menu",whyMatch:"Pourquoi ce choix",evidence:"Sources",addCart:"Ajouter au panier démo",added:"Ajouté au panier démo",moreQuestion:"Souhaitez-vous autre chose de ce restaurant ?",moreDescription:"Parcourez les autres menus compatibles du même restaurant ou passez à la livraison.",yesMore:"Oui, voir plus",noDelivery:"Non, passer à la livraison",moreFrom:"Plus de ce restaurant",swipeMore:"Faites glisser les menus compatibles du même restaurant.",noMore:"Rien d’autre, passer à la livraison",confirmDelivery:"Confirmer la livraison",finalReview:"Vérification finale",readyCheckout:"Prêt à payer",proceedPayment:"Passer au paiement",demoPayment:"Paiement démo, aucun débit réel",paymentTitle:"Finaliser la commande démo",pay:"Payer",simulateFailure:"Simuler un échec",orderConfirmed:"Votre première commande coréenne est lancée.",arrival:"Arrivée estimée",handoff:"Remise",anotherOrder:"Nouvelle commande",conversation:"Voir la conversation"},
  Deutsch: { buddy:"Dein Begleiter für koreanisches Essen",ready:"Deine Lieferangaben sind bereit",checking:"Menüdetails werden geprüft…",hello:"Hallo, ich bin YOBI. Erzähl mir vom Gericht oder von deiner heutigen Stimmung; ich finde belegte Demo-Optionen.",you:"Du",ask:"YOBI fragen",placeholder:"Ich sah ein rotes Reiskuchengericht…",demoQuestion:"Demo-Frage testen",orderBuilder:"Bestellung zusammenstellen",close:"Schließen",options:"Optionen",delivery:"Lieferung",review:"Prüfung",spice:"Schärfestufe",chooseMenu:"Dieses Menü wählen",whyMatch:"Warum passend",evidence:"Quellen",addCart:"Zum Demo-Warenkorb",added:"Zum Demo-Warenkorb hinzugefügt",moreQuestion:"Möchtest du noch etwas von diesem Restaurant?",moreDescription:"Weitere passende Menüs desselben Restaurants ansehen oder zur Lieferung gehen.",yesMore:"Ja, mehr Menüs",noDelivery:"Nein, weiter zur Lieferung",moreFrom:"Mehr von diesem Restaurant",swipeMore:"Wische durch passende Menüs desselben Restaurants.",noMore:"Nichts mehr, weiter zur Lieferung",confirmDelivery:"Lieferung bestätigen",finalReview:"Letzte Prüfung",readyCheckout:"Bereit zum Bezahlen",proceedPayment:"Weiter zur Zahlung",demoPayment:"Demo-Zahlung, keine echte Belastung",paymentTitle:"Demo-Bestellung abschließen",pay:"Bezahlen",simulateFailure:"Fehler simulieren",orderConfirmed:"Deine erste K-Food-Bestellung ist unterwegs.",arrival:"Voraussichtliche Ankunft",handoff:"Übergabe",anotherOrder:"Neue Bestellung",conversation:"Unterhaltung ansehen"},
  Italiano: { buddy:"Il tuo compagno per il cibo coreano",ready:"Il contesto di consegna è pronto",checking:"Controllo del menu…",hello:"Ciao, sono YOBI. Raccontami il piatto che ricordi o cosa desideri stasera; troverò opzioni demo supportate da fonti.",you:"Tu",ask:"Chiedi a YOBI",placeholder:"Ho visto un piatto rosso di gnocchi di riso…",demoQuestion:"Prova la domanda demo",orderBuilder:"Crea ordine",close:"Chiudi",options:"opzioni",delivery:"consegna",review:"riepilogo",spice:"Livello di piccante",chooseMenu:"Scegli questo menu",whyMatch:"Perché è adatto",evidence:"Fonti",addCart:"Aggiungi al carrello demo",added:"Aggiunto al carrello demo",moreQuestion:"Vuoi altro da questo ristorante?",moreDescription:"Esplora altri menu compatibili dello stesso ristorante o continua alla consegna.",yesMore:"Sì, mostra altri menu",noDelivery:"No, continua alla consegna",moreFrom:"Altro da questo ristorante",swipeMore:"Scorri i menu compatibili dello stesso ristorante.",noMore:"Nient’altro, continua alla consegna",confirmDelivery:"Conferma consegna",finalReview:"Riepilogo finale",readyCheckout:"Pronto al pagamento",proceedPayment:"Vai al pagamento",demoPayment:"Pagamento demo, nessun addebito reale",paymentTitle:"Completa l’ordine demo",pay:"Paga",simulateFailure:"Simula errore",orderConfirmed:"Il tuo primo ordine coreano è partito.",arrival:"Arrivo previsto",handoff:"Consegna",anotherOrder:"Nuovo ordine",conversation:"Vedi conversazione"},
  Português: { buddy:"Seu parceiro de comida coreana",ready:"Seu contexto de entrega está pronto",checking:"Verificando o menu…",hello:"Olá, eu sou YOBI. Conte o prato de que se lembra ou o que deseja hoje; mostrarei opções de demonstração com evidências.",you:"Você",ask:"Pergunte ao YOBI",placeholder:"Vi um prato vermelho de bolinho de arroz…",demoQuestion:"Testar pergunta de demo",orderBuilder:"Montar pedido",close:"Fechar",options:"opções",delivery:"entrega",review:"revisão",spice:"Nível de picância",chooseMenu:"Escolher este menu",whyMatch:"Por que combina",evidence:"Fontes",addCart:"Adicionar ao carrinho demo",added:"Adicionado ao carrinho demo",moreQuestion:"Quer mais algo deste restaurante?",moreDescription:"Veja outros menus compatíveis do mesmo restaurante ou siga para a entrega.",yesMore:"Sim, mostrar mais",noDelivery:"Não, seguir para entrega",moreFrom:"Mais deste restaurante",swipeMore:"Deslize pelos menus compatíveis do mesmo restaurante.",noMore:"Nada mais; seguir para entrega",confirmDelivery:"Confirmar entrega",finalReview:"Revisão final",readyCheckout:"Pronto para pagar",proceedPayment:"Ir ao pagamento",demoPayment:"Pagamento demo, sem cobrança real",paymentTitle:"Concluir pedido demo",pay:"Pagar",simulateFailure:"Simular falha",orderConfirmed:"Seu primeiro pedido coreano foi feito.",arrival:"Chegada estimada",handoff:"Entrega",anotherOrder:"Novo pedido",conversation:"Ver conversa"},
  "ไทย": { buddy:"เพื่อนคู่ใจเรื่องอาหารเกาหลี",ready:"ข้อมูลจัดส่งพร้อมแล้ว",checking:"กำลังตรวจสอบเมนู…",hello:"สวัสดี ฉันคือ YOBI บอกอาหารที่จำได้หรือสิ่งที่อยากกินคืนนี้ แล้วฉันจะแนะนำตัวเลือกเดโมที่มีหลักฐาน",you:"คุณ",ask:"ถาม YOBI",placeholder:"ฉันเห็นต็อกสีแดงข้างถนน…",demoQuestion:"ลองคำถามเดโม",orderBuilder:"จัดคำสั่งซื้อ",close:"ปิด",options:"ตัวเลือก",delivery:"จัดส่ง",review:"ตรวจสอบ",spice:"ระดับความเผ็ด",chooseMenu:"เลือกเมนูนี้",whyMatch:"เหตุผลที่แนะนำ",evidence:"แหล่งข้อมูล",addCart:"เพิ่มในรถเข็นเดโม",added:"เพิ่มในรถเข็นเดโมแล้ว",moreQuestion:"ต้องการเมนูอื่นจากร้านนี้ไหม?",moreDescription:"ดูเมนูที่เข้ากันได้จากร้านเดิม หรือไปขั้นตอนจัดส่ง",yesMore:"ใช่ ดูเมนูเพิ่ม",noDelivery:"ไม่ ไปจัดส่ง",moreFrom:"เมนูอื่นจากร้านนี้",swipeMore:"ปัดดูเมนูที่เข้ากันได้จากร้านเดิม",noMore:"ไม่เพิ่มแล้ว ไปจัดส่ง",confirmDelivery:"ยืนยันการจัดส่ง",finalReview:"ตรวจสอบสุดท้าย",readyCheckout:"พร้อมชำระเงิน",proceedPayment:"ไปชำระเงิน",demoPayment:"ชำระเงินเดโม ไม่มีการเรียกเก็บเงินจริง",paymentTitle:"ทำคำสั่งซื้อเดโมให้เสร็จ",pay:"ชำระ",simulateFailure:"จำลองความล้มเหลว",orderConfirmed:"สั่งอาหารเกาหลีครั้งแรกแล้ว",arrival:"เวลาถึงโดยประมาณ",handoff:"การส่งมอบ",anotherOrder:"เริ่มคำสั่งซื้อใหม่",conversation:"ดูบทสนทนา"},
  "Tiếng Việt": { buddy:"Người bạn ẩm thực Hàn Quốc",ready:"Thông tin giao hàng đã sẵn sàng",checking:"Đang kiểm tra thực đơn…",hello:"Xin chào, tôi là YOBI. Hãy kể món bạn nhớ hoặc cảm giác muốn ăn tối nay; tôi sẽ đưa ra lựa chọn demo có căn cứ.",you:"Bạn",ask:"Hỏi YOBI",placeholder:"Tôi thấy một món bánh gạo đỏ trên phố…",demoQuestion:"Thử câu hỏi demo",orderBuilder:"Tạo đơn hàng",close:"Đóng",options:"tùy chọn",delivery:"giao hàng",review:"xem lại",spice:"Mức độ cay",chooseMenu:"Chọn món này",whyMatch:"Lý do phù hợp",evidence:"Nguồn bằng chứng",addCart:"Thêm vào giỏ demo",added:"Đã thêm vào giỏ demo",moreQuestion:"Bạn muốn gọi thêm món từ nhà hàng này không?",moreDescription:"Xem các món phù hợp khác cùng nhà hàng hoặc tiếp tục giao hàng.",yesMore:"Có, xem thêm",noDelivery:"Không, tiếp tục giao",moreFrom:"Thêm món từ nhà hàng này",swipeMore:"Vuốt để xem các món phù hợp cùng nhà hàng.",noMore:"Không thêm, tiếp tục giao",confirmDelivery:"Xác nhận giao hàng",finalReview:"Xem lại lần cuối",readyCheckout:"Sẵn sàng thanh toán",proceedPayment:"Tới thanh toán",demoPayment:"Thanh toán demo, không tính phí thật",paymentTitle:"Hoàn tất đơn demo",pay:"Thanh toán",simulateFailure:"Mô phỏng thất bại",orderConfirmed:"Đơn món Hàn đầu tiên đã được đặt.",arrival:"Dự kiến đến",handoff:"Bàn giao",anotherOrder:"Đặt đơn khác",conversation:"Xem hội thoại"},
  "Bahasa Indonesia": { buddy:"Teman makanan Korea Anda",ready:"Konteks pengantaran sudah siap",checking:"Memeriksa menu…",hello:"Hai, saya YOBI. Ceritakan makanan yang Anda ingat atau ingin malam ini; saya akan memberi pilihan demo yang berbasis bukti.",you:"Anda",ask:"Tanya YOBI",placeholder:"Saya melihat kue beras merah di jalan…",demoQuestion:"Coba pertanyaan demo",orderBuilder:"Susun pesanan",close:"Tutup",options:"opsi",delivery:"pengantaran",review:"tinjauan",spice:"Tingkat pedas",chooseMenu:"Pilih menu ini",whyMatch:"Alasan cocok",evidence:"Sumber bukti",addCart:"Tambah ke keranjang demo",added:"Ditambahkan ke keranjang demo",moreQuestion:"Ingin menu lain dari restoran ini?",moreDescription:"Jelajahi menu lain yang cocok dari restoran yang sama atau lanjut ke pengantaran.",yesMore:"Ya, tampilkan lainnya",noDelivery:"Tidak, lanjut pengantaran",moreFrom:"Lainnya dari restoran ini",swipeMore:"Geser menu yang cocok dari restoran yang sama.",noMore:"Tidak tambah, lanjut pengantaran",confirmDelivery:"Konfirmasi pengantaran",finalReview:"Tinjauan akhir",readyCheckout:"Siap membayar",proceedPayment:"Lanjut pembayaran",demoPayment:"Pembayaran demo, tanpa tagihan nyata",paymentTitle:"Selesaikan pesanan demo",pay:"Bayar",simulateFailure:"Simulasikan kegagalan",orderConfirmed:"Pesanan makanan Korea pertama Anda sudah dibuat.",arrival:"Perkiraan tiba",handoff:"Serah terima",anotherOrder:"Mulai pesanan lain",conversation:"Lihat percakapan"},
  "العربية": { buddy:"رفيقك للطعام الكوري",ready:"بيانات التوصيل جاهزة",checking:"جارٍ التحقق من القائمة…",hello:"مرحبًا، أنا YOBI. أخبرني عن الطبق الذي تتذكره أو ما تشتهيه الليلة، وسأقترح خيارات تجريبية موثقة.",you:"أنت",ask:"اسأل YOBI",placeholder:"رأيت طبق كعك أرز أحمر في الشارع…",demoQuestion:"جرّب سؤال العرض",orderBuilder:"إنشاء الطلب",close:"إغلاق",options:"الخيارات",delivery:"التوصيل",review:"المراجعة",spice:"مستوى الحِرّ",chooseMenu:"اختر هذه الوجبة",whyMatch:"سبب الملاءمة",evidence:"مصادر الدليل",addCart:"أضف إلى السلة التجريبية",added:"تمت الإضافة إلى السلة",moreQuestion:"هل تريد شيئًا آخر من هذا المطعم؟",moreDescription:"تصفح بقية الوجبات الملائمة من المطعم نفسه أو تابع للتوصيل.",yesMore:"نعم، اعرض المزيد",noDelivery:"لا، تابع للتوصيل",moreFrom:"المزيد من هذا المطعم",swipeMore:"مرّر لرؤية وجبات ملائمة من المطعم نفسه.",noMore:"لا مزيد، تابع للتوصيل",confirmDelivery:"تأكيد التوصيل",finalReview:"المراجعة النهائية",readyCheckout:"جاهز للدفع",proceedPayment:"متابعة إلى الدفع",demoPayment:"دفع تجريبي دون رسوم حقيقية",paymentTitle:"أكمل الطلب التجريبي",pay:"ادفع",simulateFailure:"محاكاة الفشل",orderConfirmed:"تم إرسال أول طلب طعام كوري.",arrival:"الوصول المتوقع",handoff:"التسليم",anotherOrder:"ابدأ طلبًا آخر",conversation:"عرض المحادثة"},
  "हिन्दी": { buddy:"आपका कोरियाई भोजन साथी",ready:"डिलीवरी की जानकारी तैयार है",checking:"मेनू की जाँच हो रही है…",hello:"नमस्ते, मैं YOBI हूँ। याद आने वाले खाने या आज की पसंद के बारे में बताइए; मैं प्रमाण-आधारित डेमो विकल्प दिखाऊँगा।",you:"आप",ask:"YOBI से पूछें",placeholder:"मैंने सड़क पर लाल राइस केक देखा…",demoQuestion:"डेमो सवाल आज़माएँ",orderBuilder:"ऑर्डर बनाएँ",close:"बंद करें",options:"विकल्प",delivery:"डिलीवरी",review:"समीक्षा",spice:"तीखेपन का स्तर",chooseMenu:"यह मेनू चुनें",whyMatch:"क्यों उपयुक्त",evidence:"प्रमाण स्रोत",addCart:"डेमो कार्ट में जोड़ें",added:"डेमो कार्ट में जोड़ा गया",moreQuestion:"क्या इस रेस्तरां से कुछ और चाहिए?",moreDescription:"इसी रेस्तरां के अन्य उपयुक्त मेनू देखें या डिलीवरी पर जाएँ।",yesMore:"हाँ, और मेनू दिखाएँ",noDelivery:"नहीं, डिलीवरी पर जाएँ",moreFrom:"इस रेस्तरां से और",swipeMore:"इसी रेस्तरां के उपयुक्त मेनू स्वाइप करें।",noMore:"और नहीं, डिलीवरी पर जाएँ",confirmDelivery:"डिलीवरी की पुष्टि",finalReview:"अंतिम समीक्षा",readyCheckout:"भुगतान के लिए तैयार",proceedPayment:"भुगतान पर जाएँ",demoPayment:"डेमो भुगतान, वास्तविक शुल्क नहीं",paymentTitle:"डेमो ऑर्डर पूरा करें",pay:"भुगतान",simulateFailure:"विफलता सिमुलेट करें",orderConfirmed:"आपका पहला कोरियाई भोजन ऑर्डर हो गया।",arrival:"अनुमानित आगमन",handoff:"सौंपना",anotherOrder:"नया ऑर्डर",conversation:"बातचीत देखें"},
  "Русский": { buddy:"Ваш спутник по корейской кухне",ready:"Данные доставки готовы",checking:"Проверяем меню…",hello:"Здравствуйте, я YOBI. Расскажите, какое блюдо вы помните или чего хочется сегодня; я предложу обоснованные демо-варианты.",you:"Вы",ask:"Спросить YOBI",placeholder:"Я видел на улице красные рисовые клёцки…",demoQuestion:"Попробовать демо-вопрос",orderBuilder:"Собрать заказ",close:"Закрыть",options:"опции",delivery:"доставка",review:"проверка",spice:"Уровень остроты",chooseMenu:"Выбрать это меню",whyMatch:"Почему подходит",evidence:"Источники",addCart:"Добавить в демо-корзину",added:"Добавлено в демо-корзину",moreQuestion:"Хотите что-то ещё из этого ресторана?",moreDescription:"Посмотрите другие подходящие блюда того же ресторана или перейдите к доставке.",yesMore:"Да, показать ещё",noDelivery:"Нет, перейти к доставке",moreFrom:"Ещё из этого ресторана",swipeMore:"Листайте подходящие блюда того же ресторана.",noMore:"Больше ничего, к доставке",confirmDelivery:"Подтвердить доставку",finalReview:"Итоговая проверка",readyCheckout:"Готово к оплате",proceedPayment:"Перейти к оплате",demoPayment:"Демо-оплата, без реального списания",paymentTitle:"Завершить демо-заказ",pay:"Оплатить",simulateFailure:"Имитировать сбой",orderConfirmed:"Ваш первый заказ корейской еды принят.",arrival:"Ожидаемое прибытие",handoff:"Передача",anotherOrder:"Новый заказ",conversation:"Посмотреть разговор"},
};

const profileEn: ProfileCopy = { step:"2 of 2 · Your food & delivery context",title:"What should YOBI keep in mind?",age:"Age range",religion:"Religion (optional)",dietary:"Dietary needs",vegan:"Vegan",allergies:"Allergies",severity:"Severity for all selected allergies",spice:"Spice tolerance",favourites:"Favourite comfort foods",address:"Delivery address",required:"Required before recommendations",hotel:"Hotel name",image:"Booking image",road:"Road address",consent:"I agree to process this synthetic demo profile and address for this browser session.",check:"Check delivery address",changeLocale:"Change language or country" };
const profilePacks: Record<SupportedLanguage, ProfileCopy> = {
  English: profileEn,
  "한국어": {step:"2/2 · 음식 및 배달 정보",title:"YOBI가 무엇을 기억하면 좋을까요?",age:"연령대",religion:"종교 (선택)",dietary:"식이 정보",vegan:"비건",allergies:"알레르기",severity:"선택한 모든 알레르기의 공통 심각도",spice:"매운맛 선호도",favourites:"좋아하는 편안한 음식",address:"배달 주소",required:"추천 전 필수",hotel:"호텔명",image:"예약 이미지",road:"도로명 주소",consent:"이 브라우저 세션에서 합성 데모 프로필과 주소 처리에 동의합니다.",check:"배달 주소 확인",changeLocale:"언어 또는 국가 변경"},
  "日本語": {step:"2/2・食事と配達情報",title:"YOBIに覚えてほしいことは？",age:"年齢層",religion:"宗教（任意）",dietary:"食事条件",vegan:"ヴィーガン",allergies:"アレルギー",severity:"選択した全アレルギーの共通重症度",spice:"辛さの好み",favourites:"好きな食べ物",address:"配達先",required:"おすすめ前に必須",hotel:"ホテル名",image:"予約画像",road:"道路住所",consent:"このブラウザで合成デモ情報を処理することに同意します。",check:"配達先を確認",changeLocale:"言語・国を変更"},
  "中文（简体）": {step:"第 2/2 步 · 饮食与配送信息",title:"希望 YOBI 记住什么？",age:"年龄段",religion:"宗教（可选）",dietary:"饮食需求",vegan:"纯素",allergies:"过敏原",severity:"所有已选过敏原的统一严重程度",spice:"辣度偏好",favourites:"喜欢的家常食物",address:"配送地址",required:"推荐前必填",hotel:"酒店名称",image:"预订图片",road:"道路地址",consent:"我同意在本浏览器会话中处理合成演示信息。",check:"核对配送地址",changeLocale:"更改语言或国家"},
  "中文（繁體）": {step:"第 2/2 步 · 飲食與配送資訊",title:"希望 YOBI 記住什麼？",age:"年齡層",religion:"宗教（選填）",dietary:"飲食需求",vegan:"純素",allergies:"過敏原",severity:"所有已選過敏原的統一嚴重程度",spice:"辣度偏好",favourites:"喜歡的家常食物",address:"配送地址",required:"推薦前必填",hotel:"飯店名稱",image:"預訂圖片",road:"道路地址",consent:"我同意在本瀏覽器工作階段處理合成示範資訊。",check:"核對配送地址",changeLocale:"更改語言或國家"},
  Español: {step:"2 de 2 · Comida y entrega",title:"¿Qué debe tener en cuenta YOBI?",age:"Rango de edad",religion:"Religión (opcional)",dietary:"Necesidades alimentarias",vegan:"Vegano",allergies:"Alergias",severity:"Gravedad común para todas las alergias",spice:"Tolerancia al picante",favourites:"Comidas favoritas",address:"Dirección de entrega",required:"Obligatorio antes de recomendar",hotel:"Nombre del hotel",image:"Imagen de reserva",road:"Dirección",consent:"Acepto procesar estos datos sintéticos durante esta sesión.",check:"Comprobar dirección",changeLocale:"Cambiar idioma o país"},
  Français: {step:"2 sur 2 · Repas et livraison",title:"Que doit retenir YOBI ?",age:"Tranche d’âge",religion:"Religion (facultatif)",dietary:"Besoins alimentaires",vegan:"Végane",allergies:"Allergies",severity:"Gravité commune à toutes les allergies",spice:"Tolérance au piquant",favourites:"Plats réconfortants favoris",address:"Adresse de livraison",required:"Requis avant recommandation",hotel:"Nom de l’hôtel",image:"Image de réservation",road:"Adresse",consent:"J’accepte le traitement de ces données synthétiques pour cette session.",check:"Vérifier l’adresse",changeLocale:"Changer langue ou pays"},
  Deutsch: {step:"2 von 2 · Essen und Lieferung",title:"Was soll YOBI beachten?",age:"Altersgruppe",religion:"Religion (optional)",dietary:"Ernährungsbedürfnisse",vegan:"Vegan",allergies:"Allergien",severity:"Gemeinsamer Schweregrad aller Allergien",spice:"Schärfetoleranz",favourites:"Lieblingsgerichte",address:"Lieferadresse",required:"Vor Empfehlungen erforderlich",hotel:"Hotelname",image:"Buchungsbild",road:"Straßenadresse",consent:"Ich stimme der Verarbeitung dieser synthetischen Demodaten zu.",check:"Lieferadresse prüfen",changeLocale:"Sprache oder Land ändern"},
  Italiano: {step:"2 di 2 · Cibo e consegna",title:"Cosa deve ricordare YOBI?",age:"Fascia d’età",religion:"Religione (facoltativa)",dietary:"Esigenze alimentari",vegan:"Vegano",allergies:"Allergie",severity:"Gravità comune per tutte le allergie",spice:"Tolleranza al piccante",favourites:"Cibi preferiti",address:"Indirizzo di consegna",required:"Obbligatorio prima dei consigli",hotel:"Nome hotel",image:"Immagine prenotazione",road:"Indirizzo",consent:"Accetto il trattamento dei dati sintetici per questa sessione.",check:"Controlla indirizzo",changeLocale:"Cambia lingua o paese"},
  Português: {step:"2 de 2 · Comida e entrega",title:"O que o YOBI deve lembrar?",age:"Faixa etária",religion:"Religião (opcional)",dietary:"Necessidades alimentares",vegan:"Vegano",allergies:"Alergias",severity:"Gravidade comum para todas as alergias",spice:"Tolerância à picância",favourites:"Comidas favoritas",address:"Endereço de entrega",required:"Obrigatório antes das recomendações",hotel:"Nome do hotel",image:"Imagem da reserva",road:"Endereço",consent:"Concordo com o processamento destes dados sintéticos nesta sessão.",check:"Verificar endereço",changeLocale:"Alterar idioma ou país"},
  "ไทย": {step:"2 จาก 2 · อาหารและการจัดส่ง",title:"YOBI ควรจำอะไรไว้?",age:"ช่วงอายุ",religion:"ศาสนา (ไม่บังคับ)",dietary:"ความต้องการด้านอาหาร",vegan:"วีแกน",allergies:"อาการแพ้",severity:"ระดับความรุนแรงร่วมของอาการแพ้ทั้งหมด",spice:"ความทนต่อความเผ็ด",favourites:"อาหารโปรด",address:"ที่อยู่จัดส่ง",required:"จำเป็นก่อนแนะนำ",hotel:"ชื่อโรงแรม",image:"ภาพการจอง",road:"ที่อยู่ถนน",consent:"ฉันยินยอมให้ประมวลผลข้อมูลเดโมสังเคราะห์ในเซสชันนี้",check:"ตรวจสอบที่อยู่",changeLocale:"เปลี่ยนภาษาหรือประเทศ"},
  "Tiếng Việt": {step:"2/2 · Ăn uống và giao hàng",title:"YOBI nên ghi nhớ điều gì?",age:"Độ tuổi",religion:"Tôn giáo (không bắt buộc)",dietary:"Nhu cầu ăn uống",vegan:"Thuần chay",allergies:"Dị ứng",severity:"Mức độ chung cho mọi dị ứng",spice:"Khả năng ăn cay",favourites:"Món ăn yêu thích",address:"Địa chỉ giao hàng",required:"Bắt buộc trước khi gợi ý",hotel:"Tên khách sạn",image:"Ảnh đặt phòng",road:"Địa chỉ đường",consent:"Tôi đồng ý xử lý dữ liệu demo tổng hợp trong phiên này.",check:"Kiểm tra địa chỉ",changeLocale:"Đổi ngôn ngữ hoặc quốc gia"},
  "Bahasa Indonesia": {step:"2 dari 2 · Makanan dan pengantaran",title:"Apa yang perlu diingat YOBI?",age:"Rentang usia",religion:"Agama (opsional)",dietary:"Kebutuhan makanan",vegan:"Vegan",allergies:"Alergi",severity:"Tingkat keparahan yang sama untuk semua alergi",spice:"Toleransi pedas",favourites:"Makanan favorit",address:"Alamat pengantaran",required:"Wajib sebelum rekomendasi",hotel:"Nama hotel",image:"Gambar reservasi",road:"Alamat jalan",consent:"Saya setuju data demo sintetis diproses dalam sesi ini.",check:"Periksa alamat",changeLocale:"Ubah bahasa atau negara"},
  "العربية": {step:"2 من 2 · الطعام والتوصيل",title:"ما الذي ينبغي أن يتذكره YOBI؟",age:"الفئة العمرية",religion:"الديانة (اختياري)",dietary:"الاحتياجات الغذائية",vegan:"نباتي صرف",allergies:"الحساسيات",severity:"شدة واحدة لكل الحساسيات المختارة",spice:"تحمل الحِرّ",favourites:"الأطعمة المفضلة",address:"عنوان التوصيل",required:"مطلوب قبل التوصية",hotel:"اسم الفندق",image:"صورة الحجز",road:"عنوان الشارع",consent:"أوافق على معالجة بيانات العرض الاصطناعية في هذه الجلسة.",check:"تحقق من العنوان",changeLocale:"تغيير اللغة أو البلد"},
  "हिन्दी": {step:"2 में से 2 · भोजन और डिलीवरी",title:"YOBI को क्या याद रखना चाहिए?",age:"आयु वर्ग",religion:"धर्म (वैकल्पिक)",dietary:"आहार संबंधी ज़रूरतें",vegan:"वीगन",allergies:"एलर्जी",severity:"सभी चुनी एलर्जी की समान गंभीरता",spice:"तीखा सहने की क्षमता",favourites:"पसंदीदा भोजन",address:"डिलीवरी पता",required:"सुझाव से पहले आवश्यक",hotel:"होटल का नाम",image:"बुकिंग चित्र",road:"सड़क का पता",consent:"मैं इस सत्र में सिंथेटिक डेमो डेटा के उपयोग से सहमत हूँ।",check:"पता जाँचें",changeLocale:"भाषा या देश बदलें"},
  "Русский": {step:"2 из 2 · Еда и доставка",title:"Что должен учитывать YOBI?",age:"Возраст",religion:"Религия (необязательно)",dietary:"Пищевые требования",vegan:"Веганство",allergies:"Аллергии",severity:"Одна степень тяжести для всех аллергий",spice:"Переносимость острого",favourites:"Любимая еда",address:"Адрес доставки",required:"Обязательно до рекомендаций",hotel:"Название отеля",image:"Изображение брони",road:"Адрес",consent:"Я согласен на обработку синтетических демоданных в этом сеансе.",check:"Проверить адрес",changeLocale:"Изменить язык или страну"},
};

const dynamicPacks: Record<SupportedLanguage, DynamicCopy> = {
  English: {fallbackResult:"I found grounded choices in the synthetic demo catalog. Review the evidence and choose a menu to continue.",menuMatches:"Grounded menu matches",catalogDescription:"A synthetic catalog menu matched to your profile and delivery context.",matchReason:"Matched using your saved profile, catalog facts and current delivery context.",riskUnknown:"Kitchen cross-contamination is not verified.",evidenceDescription:"Review the evidence status and source identifier before choosing."},
  "한국어": {fallbackResult:"합성 데모 카탈로그에서 근거가 있는 선택지를 찾았어요. 근거를 확인하고 계속할 메뉴를 골라 주세요.",menuMatches:"근거 기반 추천 메뉴",catalogDescription:"프로필과 배달 정보에 맞춘 합성 카탈로그 메뉴입니다.",matchReason:"저장한 프로필, 카탈로그 정보와 현재 배달 조건을 사용해 추천했습니다.",riskUnknown:"주방 교차 오염 여부는 확인되지 않았습니다.",evidenceDescription:"선택하기 전에 근거 상태와 출처 식별자를 확인해 주세요."},
  "日本語": {fallbackResult:"合成デモカタログから根拠のある候補を見つけました。根拠を確認してメニューを選んでください。",menuMatches:"根拠に基づくおすすめ",catalogDescription:"プロフィールと配達条件に合う合成カタログメニューです。",matchReason:"保存したプロフィール、カタログ情報、配達条件を使って選びました。",riskUnknown:"厨房での交差接触は確認されていません。",evidenceDescription:"選ぶ前に根拠の状態と出典IDを確認してください。"},
  "中文（简体）": {fallbackResult:"已从合成演示目录中找到有依据的选项。请核对依据后选择菜单。",menuMatches:"有依据的菜单推荐",catalogDescription:"根据你的资料和配送条件匹配的合成目录菜单。",matchReason:"使用已保存的资料、目录事实和配送条件进行匹配。",riskUnknown:"厨房交叉接触尚未核实。",evidenceDescription:"选择前请查看依据状态和来源标识。"},
  "中文（繁體）": {fallbackResult:"已從合成示範目錄中找到有依據的選項。請核對依據後選擇菜單。",menuMatches:"有依據的菜單推薦",catalogDescription:"依你的資料和配送條件配對的合成目錄菜單。",matchReason:"使用已儲存的資料、目錄事實和配送條件配對。",riskUnknown:"廚房交叉接觸尚未核實。",evidenceDescription:"選擇前請查看依據狀態和來源識別碼。"},
  Español: {fallbackResult:"Encontré opciones fundamentadas en el catálogo demo sintético. Revisa la evidencia y elige un menú.",menuMatches:"Menús recomendados con evidencia",catalogDescription:"Menú sintético adaptado a tu perfil y entrega.",matchReason:"Coincidencia basada en tu perfil, el catálogo y la entrega actual.",riskUnknown:"La contaminación cruzada de cocina no está verificada.",evidenceDescription:"Revisa el estado y el identificador de la fuente antes de elegir."},
  Français: {fallbackResult:"J’ai trouvé des choix étayés dans le catalogue synthétique. Vérifiez les preuves puis choisissez un menu.",menuMatches:"Menus recommandés avec preuves",catalogDescription:"Menu synthétique adapté à votre profil et à la livraison.",matchReason:"Correspondance fondée sur votre profil, le catalogue et la livraison.",riskUnknown:"La contamination croisée en cuisine n’est pas vérifiée.",evidenceDescription:"Vérifiez l’état et l’identifiant de la source avant de choisir."},
  Deutsch: {fallbackResult:"Ich habe belegte Optionen im synthetischen Demo-Katalog gefunden. Prüfe die Nachweise und wähle ein Menü.",menuMatches:"Belegte Menüempfehlungen",catalogDescription:"Ein synthetisches Menü passend zu Profil und Lieferung.",matchReason:"Abgleich mit gespeichertem Profil, Katalogdaten und Lieferkontext.",riskUnknown:"Kreuzkontamination in der Küche ist nicht bestätigt.",evidenceDescription:"Prüfe Status und Quellen-ID vor der Auswahl."},
  Italiano: {fallbackResult:"Ho trovato opzioni documentate nel catalogo demo sintetico. Controlla le fonti e scegli un menu.",menuMatches:"Menu consigliati con fonti",catalogDescription:"Menu sintetico abbinato al profilo e alla consegna.",matchReason:"Abbinamento basato su profilo, catalogo e contesto di consegna.",riskUnknown:"La contaminazione incrociata in cucina non è verificata.",evidenceDescription:"Controlla stato e identificativo della fonte prima di scegliere."},
  Português: {fallbackResult:"Encontrei opções fundamentadas no catálogo demo sintético. Verifique as evidências e escolha um menu.",menuMatches:"Menus recomendados com evidências",catalogDescription:"Menu sintético compatível com seu perfil e entrega.",matchReason:"Correspondência com perfil, catálogo e contexto de entrega.",riskUnknown:"A contaminação cruzada na cozinha não foi verificada.",evidenceDescription:"Confira o estado e o identificador da fonte antes de escolher."},
  "ไทย": {fallbackResult:"พบตัวเลือกที่มีหลักฐานจากแคตตาล็อกเดโมสังเคราะห์ โปรดตรวจสอบข้อมูลแล้วเลือกเมนู",menuMatches:"เมนูแนะนำที่มีหลักฐาน",catalogDescription:"เมนูสังเคราะห์ที่ตรงกับโปรไฟล์และการจัดส่ง",matchReason:"จับคู่จากโปรไฟล์ ข้อมูลแคตตาล็อก และเงื่อนไขจัดส่ง",riskUnknown:"ยังไม่ได้ยืนยันการปนเปื้อนข้ามในครัว",evidenceDescription:"ตรวจสอบสถานะและรหัสแหล่งข้อมูลก่อนเลือก"},
  "Tiếng Việt": {fallbackResult:"Đã tìm thấy lựa chọn có căn cứ trong danh mục demo tổng hợp. Hãy xem bằng chứng rồi chọn món.",menuMatches:"Gợi ý món có căn cứ",catalogDescription:"Món tổng hợp phù hợp với hồ sơ và giao hàng.",matchReason:"Ghép theo hồ sơ, dữ kiện danh mục và bối cảnh giao hàng.",riskUnknown:"Chưa xác minh lây nhiễm chéo trong bếp.",evidenceDescription:"Kiểm tra trạng thái và mã nguồn trước khi chọn."},
  "Bahasa Indonesia": {fallbackResult:"Pilihan berbasis bukti ditemukan di katalog demo sintetis. Tinjau bukti lalu pilih menu.",menuMatches:"Rekomendasi menu berbasis bukti",catalogDescription:"Menu sintetis yang sesuai dengan profil dan pengantaran.",matchReason:"Dicocokkan dari profil, fakta katalog, dan konteks pengantaran.",riskUnknown:"Kontaminasi silang di dapur belum diverifikasi.",evidenceDescription:"Tinjau status dan ID sumber sebelum memilih."},
  "العربية": {fallbackResult:"وجدت خيارات موثقة في الكتالوج التجريبي الاصطناعي. راجع الأدلة ثم اختر وجبة.",menuMatches:"اقتراحات قائمة موثقة",catalogDescription:"وجبة اصطناعية ملائمة لملفك وسياق التوصيل.",matchReason:"تمت المطابقة باستخدام الملف المحفوظ وحقائق الكتالوج والتوصيل.",riskUnknown:"التلوث المتبادل في المطبخ غير متحقق منه.",evidenceDescription:"راجع حالة الدليل ومعرّف المصدر قبل الاختيار."},
  "हिन्दी": {fallbackResult:"सिंथेटिक डेमो कैटलॉग में प्रमाण-आधारित विकल्प मिले हैं। प्रमाण देखकर मेनू चुनें।",menuMatches:"प्रमाण-आधारित मेनू सुझाव",catalogDescription:"आपकी प्रोफ़ाइल और डिलीवरी से मेल खाता सिंथेटिक मेनू।",matchReason:"प्रोफ़ाइल, कैटलॉग तथ्यों और डिलीवरी के आधार पर मिलान।",riskUnknown:"रसोई में क्रॉस-कंटैमिनेशन सत्यापित नहीं है।",evidenceDescription:"चुनने से पहले स्थिति और स्रोत पहचान देखें।"},
  "Русский": {fallbackResult:"В синтетическом демо-каталоге найдены обоснованные варианты. Проверьте данные и выберите меню.",menuMatches:"Обоснованные рекомендации",catalogDescription:"Синтетическое меню с учётом профиля и доставки.",matchReason:"Подбор по профилю, данным каталога и условиям доставки.",riskUnknown:"Перекрёстное загрязнение на кухне не подтверждено.",evidenceDescription:"Перед выбором проверьте статус и идентификатор источника."},
};

export function useI18n() {
  const draftLanguage = useSessionStore((state) => state.draftLanguage);
  const profileLanguage = useSessionStore((state) => state.profile?.preferred_language);
  const language = asSupportedLanguage(profileLanguage ?? draftLanguage);
  const meta = LANGUAGE_META[language];
  useEffect(() => {
    document.documentElement.lang = meta.code;
    document.documentElement.dir = meta.direction;
  }, [meta.code, meta.direction]);
  return {
    language,
    copy: packs[language],
    profileCopy: profilePacks[language],
    dynamicCopy: dynamicPacks[language],
    chatMenuCopy: getChatMenuCopy(language),
    ...getExtendedCopy(language),
    locale: meta.code,
  };
}
