import { asEffectiveLanguage, type SupportedLanguage } from "./locale";

export interface RecommendationCopy {
  selectorEyebrow: string;
  selectorTitle: string;
  selectorDescription: string;
  multiSelect: string;
  selectedSummary: string;
  selectedCount: (count: number) => string;
  clearCategory: string;
  clearAll: string;
  complete: string;
  loadingChoices: string;
  catalogFailed: string;
  savedCatalog: string;
  retry: string;
  dietaryTitle: string;
  halal: string;
  halalHelp: string;
  vegan: string;
  veganHelp: string;
  spiceTitle: string;
  spiceHelp: string;
  koreanReference: string;
  usReference: string;
  maxSpice: (level: number) => string;
  retrieving: string;
  generating: string;
  restoring: string;
  resultsTitle: string;
  searchFallbackTitle: string;
  searchFallbackDescription: string;
  noResultsTitle: string;
  noResultsDescription: string;
  failedTitle: string;
  failedDescription: string;
  chooseMenu: string;
  similar: string;
  editCriteria: string;
  compare: string;
  evidence: string;
  hideEvidence: string;
  tryAgain: string;
  matchedPreferences: string;
  halalCertified: string;
  halalScope: string;
  veganLikely: string;
  veganChecks: string;
  noHiddenRelaxation: string;
  experienceNotice: string;
  editProfile: string;
}

const en: RecommendationCopy = {
  selectorEyebrow: "Find your meal", selectorTitle: "What sounds good?", selectorDescription: "Choose the qualities you want. You can pick more than one in each section.", multiSelect: "Multiple choices are welcome", selectedSummary: "Your choices", selectedCount: (count) => `${count} selected`, clearCategory: "Clear section", clearAll: "Clear all", complete: "Show my recommendations", loadingChoices: "Loading today’s available choices…", catalogFailed: "We couldn’t load the available food choices.", savedCatalog: "Showing the most recently loaded choices. Refresh before submitting if anything looks out of date.", retry: "Try again", dietaryTitle: "Dietary preferences", halal: "Only show halal-certified restaurants", halalHelp: "Certification is checked for the restaurant or menu scope shown in this experience.", vegan: "Look for vegan options", veganHelp: "Menus with confirmed animal ingredients are excluded. Some options may still need a restaurant check.", spiceTitle: "Maximum spice level", spiceHelp: "Choose the hottest level you would be comfortable eating. Food examples are a guide, not an exact measurement.", koreanReference: "Korean examples", usReference: "U.S. examples", maxSpice: (level) => `Up to level ${level}`, retrieving: "Checking menus that fit your choices…", generating: "YOBI is reading the food Wiki and preparing your matches…", restoring: "Restoring your recommendation…", resultsTitle: "Picked for your preferences", searchFallbackTitle: "Closest matching menus", searchFallbackDescription: "The recommendation explanation could not be completed, so these are search results closest to your saved choices.", noResultsTitle: "No menu fits every choice yet", noResultsDescription: "Nothing was loosened automatically. Change one or two choices and try again.", failedTitle: "We couldn’t finish the recommendation", failedDescription: "Your choices are saved. You can retry the same request or adjust them.", chooseMenu: "Choose this menu", similar: "Show different menus", editCriteria: "Edit choices", compare: "Compare these menus", evidence: "View Wiki evidence", hideEvidence: "Hide evidence", tryAgain: "Try recommendation again", matchedPreferences: "Why it fits", halalCertified: "Halal certification included", halalScope: "Certification scope", veganLikely: "Vegan-friendly evidence found", veganChecks: "Check before ordering", noHiddenRelaxation: "YOBI keeps every active choice unless you change it.", experienceNotice: "Restaurant and order information is prepared for this experience. No real order or charge is made.", editProfile: "Edit my information",
};

const packs: Record<SupportedLanguage, RecommendationCopy> = {
  English: en,
  "한국어": {selectorEyebrow:"메뉴 찾기",selectorTitle:"어떤 음식이 끌리세요?",selectorDescription:"원하는 특징을 골라주세요. 각 항목에서 여러 개 선택할 수 있어요.",multiSelect:"여러 개 선택 가능",selectedSummary:"내가 고른 조건",selectedCount:(n)=>`${n}개 선택`,clearCategory:"이 항목 초기화",clearAll:"전체 초기화",complete:"추천 메뉴 보기",loadingChoices:"지금 선택할 수 있는 조건을 불러오는 중…",catalogFailed:"선택 가능한 음식 조건을 불러오지 못했어요.",savedCatalog:"최근에 불러온 조건을 보여드리고 있어요. 오래된 내용처럼 보이면 새로고침해 주세요.",retry:"다시 시도",dietaryTitle:"식이 선호",halal:"할랄 인증 식당만 보기",halalHelp:"이 체험에 표시된 식당 또는 메뉴 범위의 인증 정보를 확인해요.",vegan:"비건 메뉴 찾기",veganHelp:"동물성 재료가 확인된 메뉴는 제외하고, 매장 확인이 필요한 경우에는 알려드려요.",spiceTitle:"먹을 수 있는 최대 맵기",spiceHelp:"부담 없이 먹을 수 있는 가장 높은 단계를 골라주세요. 음식 예시는 감각을 돕는 참고예요.",koreanReference:"한국 음식 기준",usReference:"미국 음식 기준",maxSpice:(n)=>`${n}단계까지`,retrieving:"선택한 조건에 맞는 메뉴를 확인하고 있어요…",generating:"음식 Wiki를 읽고 잘 맞는 메뉴를 고르는 중이에요…",restoring:"추천 결과를 다시 불러오는 중…",resultsTitle:"선택하신 취향을 바탕으로 골랐어요",searchFallbackTitle:"조건에 가까운 메뉴",searchFallbackDescription:"추천 설명을 끝내지 못해, 저장된 조건에 가까운 검색 결과를 보여드려요.",noResultsTitle:"모든 조건에 맞는 메뉴를 찾지 못했어요",noResultsDescription:"조건을 몰래 완화하지 않았어요. 한두 가지를 바꿔 다시 찾아보세요.",failedTitle:"추천을 끝내지 못했어요",failedDescription:"선택한 조건은 그대로 저장되어 있어요. 같은 요청을 다시 시도하거나 조건을 바꿀 수 있어요.",chooseMenu:"이 메뉴 선택",similar:"다른 메뉴 보기",editCriteria:"조건 수정",compare:"메뉴 비교",evidence:"Wiki 근거 보기",hideEvidence:"근거 닫기",tryAgain:"추천 다시 받기",matchedPreferences:"잘 맞는 이유",halalCertified:"할랄 인증 정보 있음",halalScope:"인증 적용 범위",veganLikely:"비건 가능 근거 있음",veganChecks:"주문 전 확인 필요",noHiddenRelaxation:"직접 바꾸기 전에는 선택한 조건을 그대로 지켜요.",experienceNotice:"가게와 주문 정보는 체험을 위해 구성되어 있으며 실제 주문이나 결제는 이루어지지 않습니다.",editProfile:"내 정보 수정"},
  "日本語": {selectorEyebrow:"メニューを探す",selectorTitle:"どんな料理が食べたいですか？",selectorDescription:"希望する特徴を選んでください。各項目で複数選択できます。",multiSelect:"複数選択できます",selectedSummary:"選んだ条件",selectedCount:(n)=>`${n}件選択`,clearCategory:"この項目をクリア",clearAll:"すべてクリア",complete:"おすすめを見る",loadingChoices:"選べる条件を読み込み中…",catalogFailed:"料理の選択肢を読み込めませんでした。",savedCatalog:"前回読み込んだ選択肢を表示しています。必要なら更新してください。",retry:"再試行",dietaryTitle:"食事の希望",halal:"ハラール認証店のみ",halalHelp:"この体験に表示される店舗またはメニュー範囲の認証情報を確認します。",vegan:"ヴィーガン候補を探す",veganHelp:"動物性食材が確認された料理は除外し、店舗確認が必要な場合はお知らせします。",spiceTitle:"食べられる辛さの上限",spiceHelp:"無理なく食べられる最も辛い段階を選んでください。料理例は目安です。",koreanReference:"韓国料理の例",usReference:"米国料理の例",maxSpice:(n)=>`レベル${n}まで`,retrieving:"条件に合うメニューを確認中…",generating:"料理Wikiを読み、おすすめを準備中…",restoring:"おすすめを復元中…",resultsTitle:"好みに合わせて選びました",searchFallbackTitle:"条件に近いメニュー",searchFallbackDescription:"おすすめ説明を完了できなかったため、保存した条件に近い検索結果を表示します。",noResultsTitle:"すべての条件に合うメニューがありません",noResultsDescription:"条件は自動で緩めていません。いくつか変更して再度お試しください。",failedTitle:"おすすめを完了できませんでした",failedDescription:"条件は保存されています。同じリクエストを再試行するか編集できます。",chooseMenu:"このメニューを選ぶ",similar:"別のメニューを見る",editCriteria:"条件を編集",compare:"メニューを比較",evidence:"Wiki根拠を見る",hideEvidence:"根拠を閉じる",tryAgain:"おすすめを再試行",matchedPreferences:"合う理由",halalCertified:"ハラール認証情報あり",halalScope:"認証範囲",veganLikely:"ヴィーガン対応の根拠あり",veganChecks:"注文前に確認が必要",noHiddenRelaxation:"変更するまで、選んだ条件はすべて維持されます。",experienceNotice:"店舗と注文情報は体験用です。実際の注文や請求は行われません。",editProfile:"情報を編集"},
  "中文（简体）": {selectorEyebrow:"寻找餐点",selectorTitle:"想吃什么样的食物？",selectorDescription:"请选择喜欢的特点，每一项都可多选。",multiSelect:"支持多选",selectedSummary:"已选条件",selectedCount:(n)=>`已选 ${n} 项`,clearCategory:"清除此项",clearAll:"全部清除",complete:"查看推荐",loadingChoices:"正在加载可选条件…",catalogFailed:"无法加载食物选项。",savedCatalog:"正在显示最近加载的选项，如有过期请刷新。",retry:"重试",dietaryTitle:"饮食偏好",halal:"仅显示清真认证餐厅",halalHelp:"我们会核对此体验中所示餐厅或菜品范围的认证信息。",vegan:"寻找纯素选项",veganHelp:"排除已确认含动物成分的菜品，需要向餐厅确认时会提示。",spiceTitle:"可接受的最高辣度",spiceHelp:"请选择能轻松享用的最高等级，食物示例仅供参考。",koreanReference:"韩国食物示例",usReference:"美国食物示例",maxSpice:(n)=>`最高 ${n} 级`,retrieving:"正在查找符合条件的菜单…",generating:"YOBI 正在阅读食物 Wiki 并准备推荐…",restoring:"正在恢复推荐…",resultsTitle:"根据你的偏好为你挑选",searchFallbackTitle:"最接近条件的菜单",searchFallbackDescription:"推荐说明未能完成，以下是最接近已保存条件的搜索结果。",noResultsTitle:"暂未找到符合全部条件的菜单",noResultsDescription:"我们没有自动放宽条件，请修改一两项后重试。",failedTitle:"未能完成推荐",failedDescription:"你的条件已保存，可以重试或修改。",chooseMenu:"选择此菜单",similar:"查看其他菜单",editCriteria:"修改条件",compare:"比较菜单",evidence:"查看 Wiki 依据",hideEvidence:"收起依据",tryAgain:"重新推荐",matchedPreferences:"符合原因",halalCertified:"含清真认证信息",halalScope:"认证范围",veganLikely:"有纯素适配依据",veganChecks:"下单前需确认",noHiddenRelaxation:"除非你修改，否则所有已选条件都会保留。",experienceNotice:"餐厅和订单信息仅用于体验，不会产生真实订单或收费。",editProfile:"修改我的信息"},
  "中文（繁體）": {selectorEyebrow:"尋找餐點",selectorTitle:"想吃什麼樣的食物？",selectorDescription:"請選擇喜歡的特點，每一項都可複選。",multiSelect:"支援複選",selectedSummary:"已選條件",selectedCount:(n)=>`已選 ${n} 項`,clearCategory:"清除此項",clearAll:"全部清除",complete:"查看推薦",loadingChoices:"正在載入可選條件…",catalogFailed:"無法載入食物選項。",savedCatalog:"正在顯示最近載入的選項，如有過期請重新整理。",retry:"重試",dietaryTitle:"飲食偏好",halal:"僅顯示清真認證餐廳",halalHelp:"我們會核對此體驗所示餐廳或菜單範圍的認證資訊。",vegan:"尋找純素選項",veganHelp:"排除已確認含動物成分的餐點，需要向餐廳確認時會提示。",spiceTitle:"可接受的最高辣度",spiceHelp:"請選擇能輕鬆享用的最高等級，食物範例僅供參考。",koreanReference:"韓國食物範例",usReference:"美國食物範例",maxSpice:(n)=>`最高 ${n} 級`,retrieving:"正在查找符合條件的菜單…",generating:"YOBI 正在閱讀食物 Wiki 並準備推薦…",restoring:"正在恢復推薦…",resultsTitle:"依照你的偏好為你挑選",searchFallbackTitle:"最接近條件的菜單",searchFallbackDescription:"推薦說明未能完成，以下是最接近已儲存條件的搜尋結果。",noResultsTitle:"暫未找到符合全部條件的菜單",noResultsDescription:"我們沒有自動放寬條件，請修改一兩項後重試。",failedTitle:"未能完成推薦",failedDescription:"你的條件已儲存，可以重試或修改。",chooseMenu:"選擇此菜單",similar:"查看其他菜單",editCriteria:"修改條件",compare:"比較菜單",evidence:"查看 Wiki 依據",hideEvidence:"收起依據",tryAgain:"重新推薦",matchedPreferences:"符合原因",halalCertified:"含清真認證資訊",halalScope:"認證範圍",veganLikely:"有純素適配依據",veganChecks:"下單前需確認",noHiddenRelaxation:"除非你修改，否則所有已選條件都會保留。",experienceNotice:"餐廳和訂單資訊僅供體驗，不會產生真實訂單或收費。",editProfile:"修改我的資訊"},
  Español: {selectorEyebrow:"Encuentra tu comida",selectorTitle:"¿Qué te apetece?",selectorDescription:"Elige las características que buscas. Puedes marcar varias por sección.",multiSelect:"Puedes elegir varias",selectedSummary:"Tus elecciones",selectedCount:(n)=>`${n} seleccionadas`,clearCategory:"Borrar sección",clearAll:"Borrar todo",complete:"Ver recomendaciones",loadingChoices:"Cargando opciones disponibles…",catalogFailed:"No pudimos cargar las opciones de comida.",savedCatalog:"Mostramos las últimas opciones cargadas. Actualiza si parecen antiguas.",retry:"Reintentar",dietaryTitle:"Preferencias alimentarias",halal:"Solo restaurantes con certificación halal",halalHelp:"Comprobamos la certificación para el restaurante o menú mostrado en esta experiencia.",vegan:"Buscar opciones veganas",veganHelp:"Se excluyen platos con ingredientes animales confirmados y se avisa si hace falta consultar al restaurante.",spiceTitle:"Picante máximo",spiceHelp:"Elige el nivel más alto que comerías cómodamente. Los ejemplos son orientativos.",koreanReference:"Ejemplos coreanos",usReference:"Ejemplos de EE. UU.",maxSpice:(n)=>`Hasta nivel ${n}`,retrieving:"Buscando menús que encajen…",generating:"YOBI está leyendo la Wiki gastronómica y preparando opciones…",restoring:"Recuperando tu recomendación…",resultsTitle:"Elegidos según tus preferencias",searchFallbackTitle:"Menús más cercanos a tus condiciones",searchFallbackDescription:"No se pudo completar la explicación; mostramos resultados cercanos a tus elecciones guardadas.",noResultsTitle:"Aún no hay un menú que cumpla todo",noResultsDescription:"No relajamos condiciones automáticamente. Cambia una o dos y prueba de nuevo.",failedTitle:"No pudimos completar la recomendación",failedDescription:"Tus elecciones están guardadas. Reintenta o modifícalas.",chooseMenu:"Elegir este menú",similar:"Ver otros menús",editCriteria:"Editar condiciones",compare:"Comparar menús",evidence:"Ver evidencia Wiki",hideEvidence:"Ocultar evidencia",tryAgain:"Reintentar recomendación",matchedPreferences:"Por qué encaja",halalCertified:"Incluye certificación halal",halalScope:"Alcance de certificación",veganLikely:"Hay evidencia vegana",veganChecks:"Confirmar antes de pedir",noHiddenRelaxation:"YOBI conserva todas las condiciones hasta que las cambies.",experienceNotice:"La información de restaurantes y pedidos es para esta experiencia; no hay pedido ni cobro real.",editProfile:"Editar mis datos"},
  Français: {selectorEyebrow:"Trouver un repas",selectorTitle:"Qu’est-ce qui vous ferait plaisir ?",selectorDescription:"Choisissez les caractéristiques souhaitées. Plusieurs choix sont possibles par rubrique.",multiSelect:"Choix multiples possibles",selectedSummary:"Vos choix",selectedCount:(n)=>`${n} sélection(s)`,clearCategory:"Effacer la rubrique",clearAll:"Tout effacer",complete:"Voir les recommandations",loadingChoices:"Chargement des choix disponibles…",catalogFailed:"Impossible de charger les choix de plats.",savedCatalog:"Les derniers choix chargés sont affichés. Actualisez-les si nécessaire.",retry:"Réessayer",dietaryTitle:"Préférences alimentaires",halal:"Uniquement les restaurants certifiés halal",halalHelp:"La certification est vérifiée pour le restaurant ou le menu présenté dans cette expérience.",vegan:"Rechercher des options véganes",veganHelp:"Les plats contenant des ingrédients animaux confirmés sont exclus; une vérification auprès du restaurant peut être signalée.",spiceTitle:"Niveau de piquant maximal",spiceHelp:"Choisissez le niveau le plus élevé que vous mangeriez confortablement. Les exemples sont indicatifs.",koreanReference:"Exemples coréens",usReference:"Exemples américains",maxSpice:(n)=>`Jusqu’au niveau ${n}`,retrieving:"Recherche de menus adaptés…",generating:"YOBI consulte le Wiki culinaire et prépare vos suggestions…",restoring:"Restauration de votre recommandation…",resultsTitle:"Choisis selon vos préférences",searchFallbackTitle:"Menus les plus proches",searchFallbackDescription:"L’explication n’a pas pu être terminée; voici les résultats les plus proches de vos choix enregistrés.",noResultsTitle:"Aucun menu ne remplit encore toutes les conditions",noResultsDescription:"Aucune condition n’a été assouplie automatiquement. Modifiez-en une ou deux.",failedTitle:"La recommandation n’a pas pu aboutir",failedDescription:"Vos choix sont enregistrés. Réessayez ou modifiez-les.",chooseMenu:"Choisir ce menu",similar:"Voir d’autres menus",editCriteria:"Modifier les choix",compare:"Comparer les menus",evidence:"Voir les sources Wiki",hideEvidence:"Masquer les sources",tryAgain:"Relancer la recommandation",matchedPreferences:"Pourquoi il convient",halalCertified:"Certification halal indiquée",halalScope:"Portée de la certification",veganLikely:"Indices véganes disponibles",veganChecks:"À vérifier avant commande",noHiddenRelaxation:"YOBI conserve toutes vos conditions jusqu’à modification.",experienceNotice:"Les informations de restaurant et de commande sont préparées pour cette expérience. Aucune commande ni facturation réelle.",editProfile:"Modifier mes informations"},
  Deutsch: {selectorEyebrow:"Essen finden",selectorTitle:"Worauf hast du Appetit?",selectorDescription:"Wähle gewünschte Eigenschaften. Pro Bereich sind mehrere möglich.",multiSelect:"Mehrfachauswahl möglich",selectedSummary:"Deine Auswahl",selectedCount:(n)=>`${n} ausgewählt`,clearCategory:"Bereich leeren",clearAll:"Alles leeren",complete:"Empfehlungen anzeigen",loadingChoices:"Verfügbare Auswahl wird geladen…",catalogFailed:"Die Essensauswahl konnte nicht geladen werden.",savedCatalog:"Die zuletzt geladenen Optionen werden angezeigt. Bei Bedarf aktualisieren.",retry:"Erneut versuchen",dietaryTitle:"Ernährungswünsche",halal:"Nur halal-zertifizierte Restaurants",halalHelp:"Die Zertifizierung wird für den in dieser Erfahrung gezeigten Restaurant- oder Menüumfang geprüft.",vegan:"Vegane Optionen suchen",veganHelp:"Gerichte mit bestätigten tierischen Zutaten werden ausgeschlossen; nötige Rückfragen werden angezeigt.",spiceTitle:"Maximale Schärfe",spiceHelp:"Wähle die höchste Stufe, die du angenehm essen würdest. Beispiele dienen nur als Orientierung.",koreanReference:"Koreanische Beispiele",usReference:"US-Beispiele",maxSpice:(n)=>`Bis Stufe ${n}`,retrieving:"Passende Menüs werden geprüft…",generating:"YOBI liest das Food-Wiki und bereitet Vorschläge vor…",restoring:"Empfehlung wird wiederhergestellt…",resultsTitle:"Passend zu deinen Vorlieben",searchFallbackTitle:"Am besten passende Suchergebnisse",searchFallbackDescription:"Die Empfehlungserklärung konnte nicht abgeschlossen werden; dies sind die nächsten Suchtreffer.",noResultsTitle:"Noch kein Menü erfüllt alle Bedingungen",noResultsDescription:"Nichts wurde automatisch gelockert. Ändere ein oder zwei Bedingungen.",failedTitle:"Empfehlung konnte nicht abgeschlossen werden",failedDescription:"Deine Auswahl ist gespeichert. Erneut versuchen oder bearbeiten.",chooseMenu:"Dieses Menü wählen",similar:"Andere Menüs zeigen",editCriteria:"Auswahl bearbeiten",compare:"Menüs vergleichen",evidence:"Wiki-Belege anzeigen",hideEvidence:"Belege ausblenden",tryAgain:"Empfehlung erneut versuchen",matchedPreferences:"Warum es passt",halalCertified:"Halal-Zertifizierung angegeben",halalScope:"Zertifizierungsumfang",veganLikely:"Vegane Hinweise vorhanden",veganChecks:"Vor Bestellung prüfen",noHiddenRelaxation:"YOBI behält alle Bedingungen bei, bis du sie änderst.",experienceNotice:"Restaurant- und Bestelldaten sind für diese Erfahrung vorbereitet; es gibt keine echte Bestellung oder Abbuchung.",editProfile:"Meine Angaben ändern"},
  Italiano: {selectorEyebrow:"Trova il tuo pasto",selectorTitle:"Cosa ti va?",selectorDescription:"Scegli le caratteristiche desiderate. Puoi selezionarne più di una per sezione.",multiSelect:"Scelta multipla",selectedSummary:"Le tue scelte",selectedCount:(n)=>`${n} selezionate`,clearCategory:"Cancella sezione",clearAll:"Cancella tutto",complete:"Mostra consigli",loadingChoices:"Caricamento delle scelte disponibili…",catalogFailed:"Impossibile caricare le scelte alimentari.",savedCatalog:"Sono mostrate le ultime scelte caricate. Aggiorna se necessario.",retry:"Riprova",dietaryTitle:"Preferenze alimentari",halal:"Solo ristoranti certificati halal",halalHelp:"La certificazione viene verificata per il ristorante o menu mostrato in questa esperienza.",vegan:"Cerca opzioni vegane",veganHelp:"I piatti con ingredienti animali confermati sono esclusi; segnaliamo quando serve una verifica.",spiceTitle:"Piccante massimo",spiceHelp:"Scegli il livello più alto che mangeresti comodamente. Gli esempi sono indicativi.",koreanReference:"Esempi coreani",usReference:"Esempi USA",maxSpice:(n)=>`Fino al livello ${n}`,retrieving:"Ricerca dei menu adatti…",generating:"YOBI legge il Wiki del cibo e prepara i risultati…",restoring:"Ripristino del consiglio…",resultsTitle:"Scelti in base alle tue preferenze",searchFallbackTitle:"Menu più vicini alle condizioni",searchFallbackDescription:"La spiegazione non è stata completata; ecco i risultati più vicini alle scelte salvate.",noResultsTitle:"Nessun menu soddisfa ancora tutto",noResultsDescription:"Non abbiamo allentato le condizioni. Modificane una o due.",failedTitle:"Impossibile completare il consiglio",failedDescription:"Le scelte sono salvate. Riprova o modificale.",chooseMenu:"Scegli questo menu",similar:"Mostra altri menu",editCriteria:"Modifica scelte",compare:"Confronta menu",evidence:"Vedi fonti Wiki",hideEvidence:"Nascondi fonti",tryAgain:"Riprova consiglio",matchedPreferences:"Perché è adatto",halalCertified:"Certificazione halal indicata",halalScope:"Ambito certificazione",veganLikely:"Evidenza vegana trovata",veganChecks:"Verifica prima dell’ordine",noHiddenRelaxation:"YOBI mantiene tutte le condizioni finché non le cambi.",experienceNotice:"Le informazioni su ristoranti e ordini sono preparate per questa esperienza; nessun ordine o addebito reale.",editProfile:"Modifica i miei dati"},
  Português: {selectorEyebrow:"Encontre sua refeição",selectorTitle:"O que você quer comer?",selectorDescription:"Escolha as características desejadas. Você pode marcar várias por seção.",multiSelect:"Seleção múltipla",selectedSummary:"Suas escolhas",selectedCount:(n)=>`${n} selecionadas`,clearCategory:"Limpar seção",clearAll:"Limpar tudo",complete:"Ver recomendações",loadingChoices:"Carregando opções disponíveis…",catalogFailed:"Não foi possível carregar as opções de comida.",savedCatalog:"Mostrando as últimas opções carregadas. Atualize se necessário.",retry:"Tentar novamente",dietaryTitle:"Preferências alimentares",halal:"Somente restaurantes certificados halal",halalHelp:"A certificação é verificada para o restaurante ou menu mostrado nesta experiência.",vegan:"Buscar opções veganas",veganHelp:"Pratos com ingredientes animais confirmados são excluídos; avisamos quando é preciso confirmar com o restaurante.",spiceTitle:"Picância máxima",spiceHelp:"Escolha o nível mais alto que comeria confortavelmente. Os exemplos são apenas uma referência.",koreanReference:"Exemplos coreanos",usReference:"Exemplos dos EUA",maxSpice:(n)=>`Até o nível ${n}`,retrieving:"Verificando menus adequados…",generating:"YOBI está lendo a Wiki de comida e preparando opções…",restoring:"Restaurando sua recomendação…",resultsTitle:"Escolhidos para suas preferências",searchFallbackTitle:"Menus mais próximos",searchFallbackDescription:"A explicação não foi concluída; estes são os resultados mais próximos das escolhas salvas.",noResultsTitle:"Nenhum menu atende a tudo ainda",noResultsDescription:"Nada foi relaxado automaticamente. Mude uma ou duas escolhas.",failedTitle:"Não foi possível concluir a recomendação",failedDescription:"Suas escolhas estão salvas. Tente novamente ou edite.",chooseMenu:"Escolher este menu",similar:"Mostrar outros menus",editCriteria:"Editar escolhas",compare:"Comparar menus",evidence:"Ver evidências da Wiki",hideEvidence:"Ocultar evidências",tryAgain:"Tentar recomendação novamente",matchedPreferences:"Por que combina",halalCertified:"Certificação halal indicada",halalScope:"Escopo da certificação",veganLikely:"Evidência vegana encontrada",veganChecks:"Confirmar antes de pedir",noHiddenRelaxation:"YOBI mantém todas as escolhas até você alterá-las.",experienceNotice:"As informações de restaurantes e pedidos são preparadas para esta experiência; não há pedido ou cobrança real.",editProfile:"Editar meus dados"},
  "ไทย": {selectorEyebrow:"ค้นหามื้ออาหาร",selectorTitle:"อยากกินอะไรแบบไหน?",selectorDescription:"เลือกคุณสมบัติที่ต้องการ แต่ละหมวดเลือกได้หลายข้อ",multiSelect:"เลือกได้หลายข้อ",selectedSummary:"สิ่งที่เลือก",selectedCount:(n)=>`เลือก ${n} ข้อ`,clearCategory:"ล้างหมวดนี้",clearAll:"ล้างทั้งหมด",complete:"ดูคำแนะนำ",loadingChoices:"กำลังโหลดตัวเลือกที่มี…",catalogFailed:"โหลดตัวเลือกอาหารไม่ได้",savedCatalog:"กำลังแสดงตัวเลือกล่าสุดที่โหลดไว้ โปรดรีเฟรชหากข้อมูลเก่า",retry:"ลองอีกครั้ง",dietaryTitle:"ความต้องการด้านอาหาร",halal:"แสดงเฉพาะร้านที่ได้รับการรับรองฮาลาล",halalHelp:"ตรวจสอบขอบเขตการรับรองของร้านหรือเมนูที่แสดงในประสบการณ์นี้",vegan:"ค้นหาตัวเลือกวีแกน",veganHelp:"ตัดเมนูที่ยืนยันว่ามีส่วนผสมจากสัตว์ และแจ้งเมื่อต้องสอบถามร้าน",spiceTitle:"ระดับเผ็ดสูงสุด",spiceHelp:"เลือกระดับสูงสุดที่กินได้สบาย ตัวอย่างอาหารเป็นเพียงแนวทาง",koreanReference:"ตัวอย่างอาหารเกาหลี",usReference:"ตัวอย่างอาหารสหรัฐฯ",maxSpice:(n)=>`ไม่เกินระดับ ${n}`,retrieving:"กำลังตรวจสอบเมนูที่ตรงเงื่อนไข…",generating:"YOBI กำลังอ่านวิกิอาหารและเตรียมเมนู…",restoring:"กำลังกู้คืนคำแนะนำ…",resultsTitle:"เลือกตามความชอบของคุณ",searchFallbackTitle:"เมนูที่ใกล้เคียงที่สุด",searchFallbackDescription:"สร้างคำอธิบายไม่สำเร็จ จึงแสดงผลค้นหาที่ใกล้กับตัวเลือกที่บันทึกไว้",noResultsTitle:"ยังไม่มีเมนูที่ตรงทุกข้อ",noResultsDescription:"เราไม่ได้ผ่อนเงื่อนไขอัตโนมัติ ลองเปลี่ยนหนึ่งหรือสองข้อ",failedTitle:"ทำคำแนะนำไม่สำเร็จ",failedDescription:"ตัวเลือกถูกบันทึกแล้ว ลองอีกครั้งหรือแก้ไขได้",chooseMenu:"เลือกเมนูนี้",similar:"ดูเมนูอื่น",editCriteria:"แก้ไขตัวเลือก",compare:"เปรียบเทียบเมนู",evidence:"ดูหลักฐานจากวิกิ",hideEvidence:"ซ่อนหลักฐาน",tryAgain:"ลองแนะนำอีกครั้ง",matchedPreferences:"เหตุผลที่เหมาะ",halalCertified:"มีข้อมูลรับรองฮาลาล",halalScope:"ขอบเขตการรับรอง",veganLikely:"พบหลักฐานว่าเหมาะกับวีแกน",veganChecks:"ตรวจสอบก่อนสั่ง",noHiddenRelaxation:"YOBI จะคงทุกเงื่อนไขจนกว่าคุณจะเปลี่ยน",experienceNotice:"ข้อมูลร้านและคำสั่งซื้อจัดทำเพื่อประสบการณ์นี้ ไม่มีการสั่งหรือเรียกเก็บเงินจริง",editProfile:"แก้ไขข้อมูลของฉัน"},
  "Tiếng Việt": {selectorEyebrow:"Tìm món ăn",selectorTitle:"Bạn muốn ăn món thế nào?",selectorDescription:"Chọn những đặc điểm bạn thích. Mỗi mục có thể chọn nhiều lựa chọn.",multiSelect:"Có thể chọn nhiều",selectedSummary:"Lựa chọn của bạn",selectedCount:(n)=>`Đã chọn ${n}`,clearCategory:"Xóa mục",clearAll:"Xóa tất cả",complete:"Xem gợi ý",loadingChoices:"Đang tải các lựa chọn hiện có…",catalogFailed:"Không thể tải lựa chọn món ăn.",savedCatalog:"Đang hiển thị lựa chọn tải gần nhất. Hãy làm mới nếu cần.",retry:"Thử lại",dietaryTitle:"Sở thích ăn uống",halal:"Chỉ nhà hàng có chứng nhận halal",halalHelp:"Chứng nhận được kiểm tra theo phạm vi nhà hàng hoặc món trong trải nghiệm này.",vegan:"Tìm món thuần chay",veganHelp:"Loại món đã xác nhận có thành phần động vật và cảnh báo khi cần hỏi nhà hàng.",spiceTitle:"Mức cay tối đa",spiceHelp:"Chọn mức cao nhất bạn có thể ăn thoải mái. Ví dụ món ăn chỉ để tham khảo.",koreanReference:"Ví dụ Hàn Quốc",usReference:"Ví dụ Hoa Kỳ",maxSpice:(n)=>`Tối đa mức ${n}`,retrieving:"Đang kiểm tra món phù hợp…",generating:"YOBI đang đọc Wiki ẩm thực và chuẩn bị gợi ý…",restoring:"Đang khôi phục gợi ý…",resultsTitle:"Được chọn theo sở thích của bạn",searchFallbackTitle:"Món gần với điều kiện nhất",searchFallbackDescription:"Không thể hoàn tất phần giải thích; đây là kết quả tìm kiếm gần nhất với lựa chọn đã lưu.",noResultsTitle:"Chưa có món đáp ứng mọi điều kiện",noResultsDescription:"Không điều kiện nào được tự động nới lỏng. Hãy đổi một hoặc hai mục.",failedTitle:"Không thể hoàn tất gợi ý",failedDescription:"Lựa chọn đã được lưu. Bạn có thể thử lại hoặc chỉnh sửa.",chooseMenu:"Chọn món này",similar:"Xem món khác",editCriteria:"Sửa lựa chọn",compare:"So sánh món",evidence:"Xem bằng chứng Wiki",hideEvidence:"Ẩn bằng chứng",tryAgain:"Thử gợi ý lại",matchedPreferences:"Vì sao phù hợp",halalCertified:"Có thông tin chứng nhận halal",halalScope:"Phạm vi chứng nhận",veganLikely:"Có bằng chứng phù hợp thuần chay",veganChecks:"Cần kiểm tra trước khi đặt",noHiddenRelaxation:"YOBI giữ mọi điều kiện cho đến khi bạn thay đổi.",experienceNotice:"Thông tin nhà hàng và đơn hàng được chuẩn bị cho trải nghiệm này; không có đơn hay khoản phí thật.",editProfile:"Sửa thông tin"},
  "Bahasa Indonesia": {selectorEyebrow:"Cari makanan",selectorTitle:"Ingin makanan seperti apa?",selectorDescription:"Pilih ciri yang Anda inginkan. Tiap bagian dapat dipilih lebih dari satu.",multiSelect:"Bisa pilih beberapa",selectedSummary:"Pilihan Anda",selectedCount:(n)=>`${n} dipilih`,clearCategory:"Bersihkan bagian",clearAll:"Bersihkan semua",complete:"Lihat rekomendasi",loadingChoices:"Memuat pilihan yang tersedia…",catalogFailed:"Pilihan makanan tidak dapat dimuat.",savedCatalog:"Menampilkan pilihan terakhir yang dimuat. Segarkan jika perlu.",retry:"Coba lagi",dietaryTitle:"Preferensi makanan",halal:"Hanya restoran bersertifikat halal",halalHelp:"Sertifikasi diperiksa untuk cakupan restoran atau menu dalam pengalaman ini.",vegan:"Cari opsi vegan",veganHelp:"Menu dengan bahan hewani terkonfirmasi dikecualikan; kami memberi tahu jika perlu konfirmasi restoran.",spiceTitle:"Tingkat pedas maksimum",spiceHelp:"Pilih tingkat tertinggi yang nyaman Anda makan. Contoh hanya panduan.",koreanReference:"Contoh Korea",usReference:"Contoh AS",maxSpice:(n)=>`Hingga tingkat ${n}`,retrieving:"Memeriksa menu yang sesuai…",generating:"YOBI membaca Wiki makanan dan menyiapkan pilihan…",restoring:"Memulihkan rekomendasi…",resultsTitle:"Dipilih sesuai preferensi Anda",searchFallbackTitle:"Menu terdekat dengan syarat",searchFallbackDescription:"Penjelasan rekomendasi tidak selesai; ini hasil pencarian terdekat dengan pilihan tersimpan.",noResultsTitle:"Belum ada menu yang memenuhi semua syarat",noResultsDescription:"Tidak ada syarat yang dilonggarkan otomatis. Ubah satu atau dua pilihan.",failedTitle:"Rekomendasi tidak dapat diselesaikan",failedDescription:"Pilihan Anda tersimpan. Coba lagi atau ubah.",chooseMenu:"Pilih menu ini",similar:"Tampilkan menu lain",editCriteria:"Ubah pilihan",compare:"Bandingkan menu",evidence:"Lihat bukti Wiki",hideEvidence:"Sembunyikan bukti",tryAgain:"Coba rekomendasi lagi",matchedPreferences:"Alasan cocok",halalCertified:"Ada informasi sertifikasi halal",halalScope:"Cakupan sertifikasi",veganLikely:"Ada bukti cocok untuk vegan",veganChecks:"Periksa sebelum memesan",noHiddenRelaxation:"YOBI mempertahankan semua syarat sampai Anda mengubahnya.",experienceNotice:"Informasi restoran dan pesanan disiapkan untuk pengalaman ini; tidak ada pesanan atau tagihan nyata.",editProfile:"Edit informasi saya"},
  "العربية": {selectorEyebrow:"ابحث عن وجبتك",selectorTitle:"ما الطعام الذي ترغب فيه؟",selectorDescription:"اختر الصفات التي تريدها. يمكنك اختيار أكثر من خيار في كل قسم.",multiSelect:"يمكن اختيار عدة خيارات",selectedSummary:"اختياراتك",selectedCount:(n)=>`${n} محددة`,clearCategory:"مسح القسم",clearAll:"مسح الكل",complete:"عرض الاقتراحات",loadingChoices:"جارٍ تحميل الخيارات المتاحة…",catalogFailed:"تعذر تحميل خيارات الطعام.",savedCatalog:"نعرض آخر خيارات تم تحميلها. حدّثها إذا بدت قديمة.",retry:"إعادة المحاولة",dietaryTitle:"التفضيلات الغذائية",halal:"عرض المطاعم المعتمدة حلال فقط",halalHelp:"يتم التحقق من اعتماد نطاق المطعم أو الوجبة الظاهر في هذه التجربة.",vegan:"البحث عن خيارات نباتية صرف",veganHelp:"تُستبعد الوجبات ذات المكونات الحيوانية المؤكدة، ونوضح متى يلزم سؤال المطعم.",spiceTitle:"أعلى مستوى حار",spiceHelp:"اختر أعلى مستوى يمكنك تناوله براحة. أمثلة الطعام إرشادية فقط.",koreanReference:"أمثلة كورية",usReference:"أمثلة أمريكية",maxSpice:(n)=>`حتى المستوى ${n}`,retrieving:"جارٍ فحص القوائم المناسبة…",generating:"يقرأ YOBI موسوعة الطعام ويجهز الاختيارات…",restoring:"جارٍ استعادة الاقتراح…",resultsTitle:"اختيارات تناسب تفضيلاتك",searchFallbackTitle:"أقرب القوائم إلى شروطك",searchFallbackDescription:"تعذر إكمال شرح الاقتراح، لذا نعرض أقرب نتائج البحث إلى اختياراتك المحفوظة.",noResultsTitle:"لا توجد وجبة تطابق جميع الشروط بعد",noResultsDescription:"لم نخفف أي شرط تلقائيًا. غيّر خيارًا أو اثنين.",failedTitle:"تعذر إكمال الاقتراح",failedDescription:"اختياراتك محفوظة. يمكنك المحاولة مجددًا أو تعديلها.",chooseMenu:"اختيار هذه الوجبة",similar:"عرض وجبات أخرى",editCriteria:"تعديل الاختيارات",compare:"مقارنة الوجبات",evidence:"عرض أدلة الموسوعة",hideEvidence:"إخفاء الأدلة",tryAgain:"إعادة الاقتراح",matchedPreferences:"سبب الملاءمة",halalCertified:"توجد معلومات اعتماد حلال",halalScope:"نطاق الاعتماد",veganLikely:"توجد أدلة ملاءمة نباتية",veganChecks:"تحقق قبل الطلب",noHiddenRelaxation:"يحافظ YOBI على كل الشروط حتى تغيّرها.",experienceNotice:"معلومات المطاعم والطلبات معدّة لهذه التجربة؛ لا يوجد طلب أو رسم حقيقي.",editProfile:"تعديل معلوماتي"},
  "हिन्दी": {selectorEyebrow:"अपना भोजन खोजें",selectorTitle:"आप क्या खाना चाहेंगे?",selectorDescription:"मनचाही विशेषताएँ चुनें। हर भाग में एक से अधिक चुन सकते हैं।",multiSelect:"कई विकल्प चुन सकते हैं",selectedSummary:"आपके चुनाव",selectedCount:(n)=>`${n} चुने`,clearCategory:"यह भाग साफ़ करें",clearAll:"सब साफ़ करें",complete:"सुझाव देखें",loadingChoices:"उपलब्ध विकल्प लोड हो रहे हैं…",catalogFailed:"भोजन विकल्प लोड नहीं हुए।",savedCatalog:"हाल में लोड हुए विकल्प दिख रहे हैं। पुराने लगें तो रीफ़्रेश करें।",retry:"फिर कोशिश करें",dietaryTitle:"आहार पसंद",halal:"केवल हलाल-प्रमाणित रेस्तरां",halalHelp:"इस अनुभव में दिखाए गए रेस्तरां या मेनू के प्रमाणन दायरे की जाँच होती है।",vegan:"वीगन विकल्प खोजें",veganHelp:"पुष्ट पशु सामग्री वाले व्यंजन हटते हैं और रेस्तरां से पूछना हो तो बताया जाता है।",spiceTitle:"अधिकतम तीखापन",spiceHelp:"वह सबसे ऊँचा स्तर चुनें जिसे आराम से खा सकें। उदाहरण केवल मार्गदर्शक हैं।",koreanReference:"कोरियाई उदाहरण",usReference:"अमेरिकी उदाहरण",maxSpice:(n)=>`स्तर ${n} तक`,retrieving:"आपकी पसंद से मिलते मेनू जाँचे जा रहे हैं…",generating:"YOBI भोजन Wiki पढ़कर सुझाव तैयार कर रहा है…",restoring:"सुझाव वापस लाया जा रहा है…",resultsTitle:"आपकी पसंद के लिए चुने गए",searchFallbackTitle:"शर्तों से सबसे नज़दीकी मेनू",searchFallbackDescription:"सुझाव का विवरण पूरा नहीं हुआ, इसलिए सहेजी पसंद के सबसे नज़दीकी खोज परिणाम दिख रहे हैं।",noResultsTitle:"अभी कोई मेनू सभी शर्तें पूरी नहीं करता",noResultsDescription:"कोई शर्त अपने आप ढीली नहीं की गई। एक-दो चुनाव बदलें।",failedTitle:"सुझाव पूरा नहीं हो सका",failedDescription:"आपके चुनाव सहेजे हैं। फिर कोशिश करें या बदलें।",chooseMenu:"यह मेनू चुनें",similar:"दूसरे मेनू दिखाएँ",editCriteria:"चुनाव बदलें",compare:"मेनू तुलना",evidence:"Wiki प्रमाण देखें",hideEvidence:"प्रमाण छिपाएँ",tryAgain:"सुझाव फिर पाएँ",matchedPreferences:"क्यों उपयुक्त",halalCertified:"हलाल प्रमाणन जानकारी उपलब्ध",halalScope:"प्रमाणन दायरा",veganLikely:"वीगन अनुकूल प्रमाण मिला",veganChecks:"ऑर्डर से पहले जाँचें",noHiddenRelaxation:"आपके बदलने तक YOBI सभी शर्तें रखता है।",experienceNotice:"रेस्तरां और ऑर्डर की जानकारी इस अनुभव के लिए तैयार है; कोई वास्तविक ऑर्डर या शुल्क नहीं।",editProfile:"मेरी जानकारी बदलें"},
  "Русский": {selectorEyebrow:"Найти блюдо",selectorTitle:"Чего вам хочется?",selectorDescription:"Выберите желаемые свойства. В каждом разделе можно отметить несколько.",multiSelect:"Можно выбрать несколько",selectedSummary:"Ваш выбор",selectedCount:(n)=>`Выбрано: ${n}`,clearCategory:"Очистить раздел",clearAll:"Очистить всё",complete:"Показать рекомендации",loadingChoices:"Загружаем доступные варианты…",catalogFailed:"Не удалось загрузить варианты блюд.",savedCatalog:"Показаны последние загруженные варианты. Обновите при необходимости.",retry:"Повторить",dietaryTitle:"Пищевые предпочтения",halal:"Только рестораны с сертификатом халяль",halalHelp:"Проверяется сертификация ресторана или меню в пределах, показанных в этом демо.",vegan:"Искать веганские варианты",veganHelp:"Блюда с подтверждёнными животными ингредиентами исключаются; необходимость уточнения отмечается.",spiceTitle:"Максимальная острота",spiceHelp:"Выберите самый высокий комфортный уровень. Примеры блюд служат ориентиром.",koreanReference:"Корейские примеры",usReference:"Примеры США",maxSpice:(n)=>`До уровня ${n}`,retrieving:"Проверяем подходящие меню…",generating:"YOBI читает пищевую Wiki и готовит варианты…",restoring:"Восстанавливаем рекомендацию…",resultsTitle:"Подобрано по вашим предпочтениям",searchFallbackTitle:"Ближайшие к условиям меню",searchFallbackDescription:"Объяснение рекомендации не завершилось, поэтому показаны ближайшие результаты поиска.",noResultsTitle:"Пока нет меню под все условия",noResultsDescription:"Условия не смягчались автоматически. Измените один-два пункта.",failedTitle:"Не удалось завершить рекомендацию",failedDescription:"Ваш выбор сохранён. Повторите или измените его.",chooseMenu:"Выбрать это меню",similar:"Показать другие меню",editCriteria:"Изменить условия",compare:"Сравнить меню",evidence:"Показать данные Wiki",hideEvidence:"Скрыть данные",tryAgain:"Повторить рекомендацию",matchedPreferences:"Почему подходит",halalCertified:"Есть данные сертификации халяль",halalScope:"Область сертификации",veganLikely:"Есть данные о веганском варианте",veganChecks:"Уточнить перед заказом",noHiddenRelaxation:"YOBI сохраняет все условия, пока вы их не измените.",experienceNotice:"Сведения о ресторанах и заказах подготовлены для этого опыта; реального заказа и списания нет.",editProfile:"Изменить мои данные"},
};

export function getRecommendationCopy(language: SupportedLanguage) {
  const effective = asEffectiveLanguage(language);
  const copy = { ...packs[effective] };
  if (effective === "English") {
    return {
      ...copy,
      halalHelp: "Menus marked halal-friendly are included.",
      spiceTitle: "Preferred spice level",
      spiceHelp: "Compare the menu with the familiar spice baseline for your selected country.",
      experienceNotice: "Review the menu and delivery details before continuing.",
    };
  }
  if (effective === "한국어") {
    return {
      ...copy,
      halalHelp: "할랄 친화 메뉴만 보여드려요.",
      spiceTitle: "선호하는 맵기",
      spiceHelp: "선택한 국가에서 익숙한 맵기를 기준으로 비교해 고르세요.",
      experienceNotice: "계속하기 전 메뉴와 배달 정보를 확인해 주세요.",
    };
  }
  return {
    ...copy,
    halalHelp: "ハラール対応のメニューだけを表示します。",
    spiceTitle: "好みの辛さ",
    spiceHelp: "選択した国で慣れ親しんだ辛さを基準に選んでください。",
    experienceNotice: "続ける前にメニューと配達情報を確認してください。",
  };
}

const conflictPacks: Record<SupportedLanguage, string> = {
  English: "One selected ingredient conflicts with the halal or vegan filter. Remove the ingredient or turn off that filter to continue.",
  "한국어": "선택한 주재료가 할랄 또는 비건 조건과 맞지 않아요. 해당 재료를 빼거나 식이 조건을 꺼주세요.",
  "日本語": "選んだ主材料がハラールまたはヴィーガン条件と矛盾しています。材料を外すか条件をオフにしてください。",
  "中文（简体）": "所选主料与清真或纯素条件冲突。请取消该主料或关闭相应条件。",
  "中文（繁體）": "所選主料與清真或純素條件衝突。請取消該主料或關閉相應條件。",
  Español: "Un ingrediente principal entra en conflicto con el filtro halal o vegano. Quita el ingrediente o desactiva ese filtro.",
  Français: "Un ingrédient principal est incompatible avec le filtre halal ou végane. Retirez-le ou désactivez ce filtre.",
  Deutsch: "Eine Hauptzutat widerspricht dem Halal- oder Vegan-Filter. Entferne die Zutat oder deaktiviere den Filter.",
  Italiano: "Un ingrediente principale è in conflitto con il filtro halal o vegano. Rimuovilo o disattiva il filtro.",
  Português: "Um ingrediente principal entra em conflito com o filtro halal ou vegano. Remova-o ou desative o filtro.",
  "ไทย": "วัตถุดิบหลักที่เลือกขัดกับตัวกรองฮาลาลหรือวีแกน โปรดนำวัตถุดิบออกหรือปิดตัวกรองนั้น",
  "Tiếng Việt": "Một nguyên liệu chính xung đột với bộ lọc halal hoặc thuần chay. Hãy bỏ nguyên liệu hoặc tắt bộ lọc đó.",
  "Bahasa Indonesia": "Satu bahan utama bertentangan dengan filter halal atau vegan. Hapus bahan tersebut atau nonaktifkan filternya.",
  "العربية": "يتعارض أحد المكونات الرئيسية مع شرط الحلال أو النباتي الصرف. أزل المكون أو أوقف الشرط للمتابعة.",
  "हिन्दी": "चुनी हुई मुख्य सामग्री हलाल या वीगन फ़िल्टर से टकराती है। सामग्री हटाएँ या वह फ़िल्टर बंद करें।",
  "Русский": "Один из основных ингредиентов не совместим с фильтром халяль или веган. Уберите ингредиент или отключите фильтр.",
};

export function getRecommendationConflictCopy(language: SupportedLanguage) {
  return conflictPacks[asEffectiveLanguage(language)];
}

const catalogChangedPacks: Record<SupportedLanguage, string> = {
  English: "The available choices were updated. Any choices that are no longer offered were removed—please review and submit again.",
  "한국어": "선택 가능한 조건이 업데이트됐어요. 더 이상 제공되지 않는 선택은 해제했으니 확인 후 다시 완료해 주세요.",
  "日本語": "選択肢が更新されました。提供終了の項目は解除したので、確認してもう一度送信してください。",
  "中文（简体）": "可选条件已更新，不再提供的选项已取消。请确认后重新提交。",
  "中文（繁體）": "可選條件已更新，不再提供的選項已取消。請確認後重新提交。",
  Español: "Las opciones disponibles se actualizaron. Quitamos las que ya no existen; revísalas y vuelve a enviar.",
  Français: "Les choix disponibles ont été mis à jour. Les choix retirés ont été désélectionnés; vérifiez puis renvoyez.",
  Deutsch: "Die verfügbaren Optionen wurden aktualisiert. Nicht mehr angebotene Auswahl wurde entfernt; bitte prüfen und erneut senden.",
  Italiano: "Le opzioni disponibili sono cambiate. Quelle non più offerte sono state rimosse; controlla e invia di nuovo.",
  Português: "As opções disponíveis foram atualizadas. As indisponíveis foram removidas; revise e envie novamente.",
  "ไทย": "ตัวเลือกที่มีอยู่ได้รับการอัปเดต ตัวเลือกที่ไม่มีแล้วถูกยกเลิก โปรดตรวจสอบและส่งอีกครั้ง",
  "Tiếng Việt": "Các lựa chọn hiện có đã được cập nhật. Mục không còn hỗ trợ đã được bỏ; hãy kiểm tra và gửi lại.",
  "Bahasa Indonesia": "Pilihan yang tersedia telah diperbarui. Pilihan yang tidak lagi tersedia sudah dihapus; tinjau lalu kirim lagi.",
  "العربية": "تم تحديث الخيارات المتاحة وإلغاء الخيارات التي لم تعد متوفرة. راجع اختياراتك ثم أرسلها مجددًا.",
  "हिन्दी": "उपलब्ध विकल्प अपडेट हुए हैं। जो विकल्प अब उपलब्ध नहीं हैं वे हटा दिए गए हैं; जाँचकर फिर भेजें।",
  "Русский": "Доступные варианты обновились. Недоступные пункты сняты; проверьте выбор и отправьте снова.",
};

export function getCatalogChangedCopy(language: SupportedLanguage) {
  return catalogChangedPacks[asEffectiveLanguage(language)];
}
